.TH BRFS 9.8
.SH NAME
brfs \- browse file system
.SH SYNOPSIS
.B /etc/brfs
[
.I filesystem
]
.SH DESCRIPTION
.I Brfs
examines a 
.I filesystem 
using a
.I pads (9.5)
interface, in the manner of
.IR pi (9.1).
It requires license
.BR T_NOCHK ;
see
.IR getplab (2).
.PP
The top level menu inspects the superblock and gives access to
other blocks by block number in the file system interpreted
as inode blocks, directory blocks,  indirect blocks or ascii blocks.
.PP
.SH SEE ALSO
.IR filsys (5)
