#!/usr/bin/env python
import re
import sys

indent = 0
more_re = re.compile(r"^: ~\">>")
less_re = re.compile(r"^: ~\"<<")
while True:
    line = sys.stdin.readline()
    if not line:
        break

    if more_re.match(line):
        indent += 1

    print("%03d %s%s" % (indent, " " * indent, line.strip()))

    if less_re.match(line):
        indent -= 1
