.TH DISPATCH 4 "Post 4.0" " "
.SH NAME
dispatch \- post directory configuration file
.SH DESCRIPTION
.I dispatch
files are used by the
.I join
module of
.IR post (1)
to access the directory.
A
.I dispatch
file contains a list of module arguments, one per line.
Argument words are separated by white space.
An open is attempted for each line in turn until one succeeds, or the
end of file is reached, in which case an error is returned.
.P
See
.IR modules (4)
for a description of
.I join
and module arguments.
.SH FILES
.PD 0
.TP 30
$POST/lib/dispatch
default configuration file
.PD
.SH SEE ALSO
post(1),
pq(3C),
modules(4).
