[package]
name        = "vitte-expander"
description = "Pipeline d’expansion des macros et des derives pour Vitte."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-expander"

keywords   = ["macro", "expansion", "vitte"]
categories = ["development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_expander"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std = []

[dependencies]
vitte-ast     = { path = "../vitte-ast" }
vitte-derive  = { path = "../vitte-derive" }
vitte-hygiene = { path = "../vitte-hygiene" }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
doc_markdown            = "allow"
too_many_lines          = "allow"
