#include "vittec/back/emit_c.h"
#include <stdio.h>

int vittec_emit_c_file(const vittec_parse_unit_t* u, const char* out_path) {
  FILE* f = fopen(out_path, "wb");
  if (!f) return 1;

  fprintf(f, "/* generated by vittec (C) */\n");
  fprintf(f, "#include <stdio.h>\n\n");

  if (u && u->has_main) {
    fprintf(f, "int main(void) {\n");
    fprintf(f, "  /* TODO: lower Vitte main -> C */\n");
    fprintf(f, "  return 0;\n");
    fprintf(f, "}\n");
  } else {
    fprintf(f, "int main(void) { return 0; }\n");
  }

  fclose(f);
  return 0;
}
