#include "translation_unit.h"

#include <string.h>

static void vitte_c17_translation_unit_set_error(
    vitte_c17_translation_unit_t *unit,
    vitte_status_t status,
    const char *code,
    const char *message,
    const char *details
) {
    if (unit != NULL) {
        vitte_error_set_details(&unit->last_error, status, code, message, details);
    }
}

void vitte_c17_translation_unit_init(
    vitte_c17_translation_unit_t *unit,
    const vitte_c17_options_t *options
) {
    if (unit == NULL) {
        return;
    }

    memset(unit, 0, sizeof(*unit));
    vitte_error_init(&unit->last_error);
    if (options != NULL) {
        unit->options = *options;
    } else {
        vitte_c17_options_init(&unit->options);
    }
}

void vitte_c17_translation_unit_reset(vitte_c17_translation_unit_t *unit) {
    if (unit == NULL) {
        return;
    }

    unit->include_count = 0u;
    unit->declaration_count = 0u;
    unit->function_count = 0u;
    vitte_error_reset(&unit->last_error);
}

const vitte_error_t *vitte_c17_translation_unit_last_error(const vitte_c17_translation_unit_t *unit) {
    return unit != NULL ? &unit->last_error : vitte_error_last();
}

vitte_status_t vitte_c17_translation_unit_emit_prelude(
    vitte_c17_translation_unit_t *unit,
    vitte_c17_writer_t *writer
) {
    vitte_status_t status;

    if (unit == NULL || writer == NULL) {
        vitte_c17_translation_unit_set_error(unit, VITTE_STATUS_ERROR_INVALID_ARGUMENT, "VITTE_C17_E_UNIT", "missing C17 translation unit or writer", NULL);
        return VITTE_STATUS_ERROR_INVALID_ARGUMENT;
    }

    if (unit->options.emit_debug_comments) {
        status = vitte_c17_write_string(writer, "/* generated by vitte bootstrap C17 backend */");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
    }

    if (unit->options.emit_includes) {
        status = vitte_c17_write_string(writer, "#include <stdbool.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stdint.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        unit->include_count += 2u;
    }

    return VITTE_STATUS_OK;
}
