#include "translation_unit.h"

#include <dirent.h>
#include <string.h>

static void vitte_c17_translation_unit_set_error(
    vitte_c17_translation_unit_t *unit,
    vitte_status_t status,
    const char *code,
    const char *message,
    const char *details
) {
    if (unit != NULL) {
        vitte_error_set_details(&unit->last_error, status, code, message, details);
    }
}

void vitte_c17_translation_unit_init(
    vitte_c17_translation_unit_t *unit,
    const vitte_c17_options_t *options
) {
    if (unit == NULL) {
        return;
    }

    memset(unit, 0, sizeof(*unit));
    vitte_error_init(&unit->last_error);
    if (options != NULL) {
        unit->options = *options;
    } else {
        vitte_c17_options_init(&unit->options);
    }
}

void vitte_c17_translation_unit_reset(vitte_c17_translation_unit_t *unit) {
    if (unit == NULL) {
        return;
    }

    unit->include_count = 0u;
    unit->declaration_count = 0u;
    unit->function_count = 0u;
    vitte_error_reset(&unit->last_error);
}

const vitte_error_t *vitte_c17_translation_unit_last_error(const vitte_c17_translation_unit_t *unit) {
    return unit != NULL ? &unit->last_error : vitte_error_last();
}

vitte_status_t vitte_c17_translation_unit_emit_prelude(
    vitte_c17_translation_unit_t *unit,
    vitte_c17_writer_t *writer
) {
    vitte_status_t status;

    if (unit == NULL || writer == NULL) {
        vitte_c17_translation_unit_set_error(unit, VITTE_STATUS_ERROR_INVALID_ARGUMENT, "VITTE_C17_E_UNIT", "missing C17 translation unit or writer", NULL);
        return VITTE_STATUS_ERROR_INVALID_ARGUMENT;
    }

    if (unit->options.emit_debug_comments) {
        status = vitte_c17_write_string(writer, "/* generated by vitte bootstrap C17 backend */");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
    }

    if (unit->options.emit_includes) {
        status = vitte_c17_write_string(writer, "#include <stdbool.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stdint.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stddef.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stdio.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stdlib.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <string.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <assert.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <sys/stat.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <dirent.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <sys/wait.h>");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#include <unistd.h>");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "char *vitte_slice(const char *text, size_t start, size_t end) { size_t length; char *out; if (text == NULL) return NULL; length = strlen(text); if (start > length) start = length; if (end > length) end = length; if (end < start) end = start; out = (char *)malloc(end - start + 1u); if (out == NULL) return NULL; memcpy(out, text + start, end - start); out[end - start] = '\\0'; return out; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static bool vitte_string_equal(const char *left, const char *right) { if (left == NULL) left = \"\"; if (right == NULL) right = \"\"; return strcmp(left, right) == 0; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_string_compare(const char *left, const char *right) { if (left == NULL) left = \"\"; if (right == NULL) right = \"\"; return strcmp(left, right); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int64_t vitte_string_find(const char *text, const char *needle) { const char *match; if (text == NULL) text = \"\"; if (needle == NULL) needle = \"\"; if (needle[0] == '\\0') return 0; match = strstr(text, needle); return match == NULL ? -1 : (int64_t)(match - text); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static char *vitte_string_concat(const char *left, const char *right) { size_t left_length; size_t right_length; char *out; if (left == NULL) left = \"\"; if (right == NULL) right = \"\"; left_length = strlen(left); right_length = strlen(right); out = (char *)malloc(left_length + right_length + 1u); if (out == NULL) abort(); memcpy(out, left, left_length); memcpy(out + left_length, right, right_length + 1u); return out; }");
        if (status == VITTE_STATUS_OK) status = vitte_c17_write_string(writer, "static char *vitte_string_from_i64(int64_t value) { char buffer[64]; int written; char *out; written = snprintf(buffer, sizeof(buffer), \"%lld\", (long long)value); if (written < 0) return \"\"; out = (char *)malloc((size_t)written + 1u); if (out == NULL) abort(); memcpy(out, buffer, (size_t)written + 1u); return out; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static bool vitte_c17_host_runtime_available(void) { return true; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static const char *vitte_c17_host_read_file(const char *path) { FILE *file; long size; char *content; size_t read_count; if (path == NULL) return \"\"; file = fopen(path, \"rb\"); if (file == NULL) return \"\"; if (fseek(file, 0, SEEK_END) != 0) { fclose(file); return \"\"; } size = ftell(file); if (size < 0 || fseek(file, 0, SEEK_SET) != 0) { fclose(file); return \"\"; } content = (char *)malloc((size_t)size + 1u); if (content == NULL) abort(); read_count = fread(content, 1u, (size_t)size, file); fclose(file); content[read_count] = '\\0'; return content; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static bool vitte_c17_host_file_exists(const char *path) { struct stat info; return path != NULL && stat(path, &info) == 0; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static bool vitte_c17_host_is_file(const char *path) { struct stat info; return path != NULL && stat(path, &info) == 0 && S_ISREG(info.st_mode); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static bool vitte_c17_host_is_directory(const char *path) { struct stat info; return path != NULL && stat(path, &info) == 0 && S_ISDIR(info.st_mode); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_write_mode(const char *path, const char *content, const char *mode) { FILE *file; size_t length; if (path == NULL || content == NULL) return -1; file = fopen(path, mode); if (file == NULL) return -1; length = strlen(content); if (length > 0u && fwrite(content, 1u, length, file) != length) { fclose(file); return -1; } return fclose(file) == 0 ? 0 : -1; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_write_file(const char *path, const char *content) { return vitte_c17_host_write_mode(path, content, \"wb\"); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_append_file(const char *path, const char *content) { return vitte_c17_host_write_mode(path, content, \"ab\"); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_mkdir_all(const char *path) { char scratch[4096]; size_t length; size_t index; if (path == NULL) return -1; length = strlen(path); if (length == 0u) return 0; if (length >= sizeof(scratch)) return -1; memcpy(scratch, path, length + 1u); for (index = 1u; index <= length; index++) { if (scratch[index] == '/' || scratch[index] == '\\0') { char saved = scratch[index]; scratch[index] = '\\0'; if (scratch[0] != '\\0' && mkdir(scratch, 0755) != 0 && !vitte_c17_host_is_directory(scratch)) return -1; scratch[index] = saved; } } return 0; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_run_argv(char *const argv[]) { pid_t pid = fork(); int wait_status = 0; if (pid < 0) return -1; if (pid == 0) { execvp(argv[0], argv); _exit(127); } if (waitpid(pid, &wait_status, 0) < 0) return -1; return WIFEXITED(wait_status) ? WEXITSTATUS(wait_status) : -1; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_system(const char *command) { int result = command != NULL ? system(command) : -1; return result >= 0 && WIFEXITED(result) ? WEXITSTATUS(result) : -1; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_emit_text_object(const char *text, const char *tool, const char *target, const char *sysroot, const char *object, const char *extension, const char *language, bool debug_enabled) { char source[4096]; char *args[18]; int index = 0; int written; if (text == NULL || tool == NULL || tool[0] == '\\0' || object == NULL || object[0] == '\\0') return -1; written = snprintf(source, sizeof(source), \"%s%s\", object, extension); if (written < 0 || (size_t)written >= sizeof(source) || vitte_c17_host_write_file(source, text) != 0) return -1; args[index++] = (char *)tool; if (target != NULL && target[0] != '\\0') { args[index++] = \"-target\"; args[index++] = (char *)target; } if (sysroot != NULL && sysroot[0] != '\\0') { args[index++] = \"--sysroot\"; args[index++] = (char *)sysroot; } if (debug_enabled) args[index++] = \"-g\"; if (language != NULL) { args[index++] = \"-x\"; args[index++] = (char *)language; } args[index++] = \"-Wno-override-module\"; args[index++] = \"-c\"; args[index++] = source; args[index++] = \"-o\"; args[index++] = (char *)object; args[index] = NULL; return vitte_c17_host_run_argv(args); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_emit_llvm_object(const char *text, const char *tool, const char *target, const char *sysroot, const char *object) { return vitte_c17_host_emit_text_object(text, tool, target, sysroot, object, \".ll\", NULL, false); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_emit_assembly_object(const char *text, const char *tool, const char *target, const char *sysroot, const char *object, bool debug_enabled) { return vitte_c17_host_emit_text_object(text, tool, target, sysroot, object, \".s\", \"assembler\", debug_enabled); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_verify_native_object(const char *object, const char *target, const char *symbol, bool require_relocations, bool require_debug) { (void)target; (void)symbol; (void)require_relocations; (void)require_debug; return vitte_c17_host_is_file(object) ? 0 : 1; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_link_executable(const char *tool, const char *target, const char *sysroot, const char *object, const char *runtime_source, const char *runtime_include, const char *executable) { char *args[18]; int index = 0; if (tool == NULL || tool[0] == '\\0' || object == NULL || executable == NULL) return -1; args[index++] = (char *)tool; if (target != NULL && target[0] != '\\0') { args[index++] = \"-target\"; args[index++] = (char *)target; } if (sysroot != NULL && sysroot[0] != '\\0') { args[index++] = \"--sysroot\"; args[index++] = (char *)sysroot; } args[index++] = (char *)object; if (vitte_c17_host_is_file(runtime_source)) { args[index++] = (char *)runtime_source; if (runtime_include != NULL && runtime_include[0] != '\\0') { args[index++] = \"-I\"; args[index++] = (char *)runtime_include; } } args[index++] = \"-o\"; args[index++] = (char *)executable; args[index] = NULL; return vitte_c17_host_run_argv(args); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_host_run_executable(const char *executable) { char *args[2]; if (executable == NULL) return -1; args[0] = (char *)executable; args[1] = NULL; return vitte_c17_host_run_argv(args); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "typedef enum vitte_value_kind { VITTE_VALUE_INT, VITTE_VALUE_STRING, VITTE_VALUE_AGGREGATE } vitte_value_kind;");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "typedef struct vitte_aggregate vitte_aggregate;");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "typedef struct vitte_value { vitte_value_kind kind; int64_t integer; const char *string; vitte_aggregate *aggregate; } vitte_value;");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "typedef struct vitte_field { const char *name; vitte_value value; } vitte_field;");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "struct vitte_aggregate { vitte_value *items; size_t count; size_t capacity; vitte_field *fields; size_t field_count; size_t field_capacity; };");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_aggregate *vitte_aggregate_new(void) { return (vitte_aggregate *)calloc(1u, sizeof(vitte_aggregate)); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_reserve_items(vitte_aggregate *value, size_t count) { size_t capacity; vitte_value *items; if (value == NULL || count <= value->capacity) return; capacity = value->capacity == 0u ? 8u : value->capacity; while (capacity < count) capacity *= 2u; items = (vitte_value *)realloc(value->items, capacity * sizeof(vitte_value)); if (items == NULL) abort(); memset(items + value->capacity, 0, (capacity - value->capacity) * sizeof(vitte_value)); value->items = items; value->capacity = capacity; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_reserve_fields(vitte_aggregate *value, size_t count) { size_t capacity; vitte_field *fields; if (value == NULL || count <= value->field_capacity) return; capacity = value->field_capacity == 0u ? 8u : value->field_capacity; while (capacity < count) capacity *= 2u; fields = (vitte_field *)realloc(value->fields, capacity * sizeof(vitte_field)); if (fields == NULL) abort(); memset(fields + value->field_capacity, 0, (capacity - value->field_capacity) * sizeof(vitte_field)); value->fields = fields; value->field_capacity = capacity; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_value *vitte_aggregate_field(vitte_aggregate *value, const char *name, bool create) { size_t i; if (value == NULL || name == NULL) return NULL; for (i = 0u; i < value->field_count; i++) if (strcmp(value->fields[i].name, name) == 0) return &value->fields[i].value; if (!create) return NULL; vitte_aggregate_reserve_fields(value, value->field_count + 1u); value->fields[value->field_count].name = name; return &value->fields[value->field_count++].value; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_append_int(vitte_aggregate *value, int64_t item) { if (value == NULL) return; vitte_aggregate_reserve_items(value, value->count + 1u); value->items[value->count].kind = VITTE_VALUE_INT; value->items[value->count++].integer = item; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_append_string(vitte_aggregate *value, const char *item) { if (value == NULL) return; vitte_aggregate_reserve_items(value, value->count + 1u); value->items[value->count].kind = VITTE_VALUE_STRING; value->items[value->count++].string = item != NULL ? item : \"\"; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int vitte_c17_compare_directory_items(const void *left, const void *right) { const vitte_value *a = (const vitte_value *)left; const vitte_value *b = (const vitte_value *)right; return strcmp(a->string != NULL ? a->string : \"\", b->string != NULL ? b->string : \"\"); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_aggregate *vitte_c17_host_list_directory(const char *path) { DIR *directory; struct dirent *entry; vitte_aggregate *out = vitte_aggregate_new(); if (path == NULL || out == NULL) return out; directory = opendir(path); if (directory == NULL) return out; while ((entry = readdir(directory)) != NULL) { size_t length; char *name; if (strcmp(entry->d_name, \".\") == 0 || strcmp(entry->d_name, \"..\") == 0) continue; length = strlen(entry->d_name); name = (char *)malloc(length + 1u); if (name == NULL) abort(); memcpy(name, entry->d_name, length + 1u); vitte_aggregate_append_string(out, name); } closedir(directory); if (out->count > 1u) qsort(out->items, out->count, sizeof(vitte_value), vitte_c17_compare_directory_items); return out; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_append_aggregate(vitte_aggregate *value, vitte_aggregate *item) { if (value == NULL) return; vitte_aggregate_reserve_items(value, value->count + 1u); value->items[value->count].kind = VITTE_VALUE_AGGREGATE; value->items[value->count++].aggregate = item; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int64_t vitte_aggregate_get_int(vitte_aggregate *value, size_t index) { return value != NULL && index < value->count ? value->items[index].integer : 0; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static const char *vitte_aggregate_get_string(vitte_aggregate *value, size_t index) { return value != NULL && index < value->count && value->items[index].string != NULL ? value->items[index].string : \"\"; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_aggregate *vitte_aggregate_get_aggregate(vitte_aggregate *value, size_t index) { return value != NULL && index < value->count ? value->items[index].aggregate : NULL; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_set_index_int(vitte_aggregate *value, size_t index, int64_t item) { if (value == NULL) return; vitte_aggregate_reserve_items(value, index + 1u); if (value->count <= index) value->count = index + 1u; value->items[index].kind = VITTE_VALUE_INT; value->items[index].integer = item; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_set_index_string(vitte_aggregate *value, size_t index, const char *item) { if (value == NULL) return; vitte_aggregate_reserve_items(value, index + 1u); if (value->count <= index) value->count = index + 1u; value->items[index].kind = VITTE_VALUE_STRING; value->items[index].string = item != NULL ? item : \"\"; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_set_index_aggregate(vitte_aggregate *value, size_t index, vitte_aggregate *item) { if (value == NULL) return; vitte_aggregate_reserve_items(value, index + 1u); if (value->count <= index) value->count = index + 1u; value->items[index].kind = VITTE_VALUE_AGGREGATE; value->items[index].aggregate = item; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int64_t vitte_aggregate_get_field_int(vitte_aggregate *value, const char *name) { vitte_value *field = vitte_aggregate_field(value, name, false); return field != NULL ? field->integer : 0; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static const char *vitte_aggregate_get_field_string(vitte_aggregate *value, const char *name) { vitte_value *field = vitte_aggregate_field(value, name, false); return field != NULL && field->string != NULL ? field->string : \"\"; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_aggregate *vitte_aggregate_get_field_aggregate(vitte_aggregate *value, const char *name) { vitte_value *field = vitte_aggregate_field(value, name, false); return field != NULL ? field->aggregate : NULL; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_set_field_int(vitte_aggregate *value, const char *name, int64_t item) { vitte_value *field = vitte_aggregate_field(value, name, true); if (field != NULL) { field->kind = VITTE_VALUE_INT; field->integer = item; } }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_set_field_string(vitte_aggregate *value, const char *name, const char *item) { vitte_value *field = vitte_aggregate_field(value, name, true); if (field != NULL) { field->kind = VITTE_VALUE_STRING; field->string = item != NULL ? item : \"\"; } }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static void vitte_aggregate_set_field_aggregate(vitte_aggregate *value, const char *name, vitte_aggregate *item) { vitte_value *field = vitte_aggregate_field(value, name, true); if (field != NULL) { field->kind = VITTE_VALUE_AGGREGATE; field->aggregate = item; } }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_aggregate *vitte_aggregate_from_argv(int argc, char **argv) { int i; vitte_aggregate *args = vitte_aggregate_new(); for (i = 1; i < argc; i++) vitte_aggregate_append_string(args, argv[i]); return args; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_aggregate *vitte_aggregate_concat(vitte_aggregate *left, vitte_aggregate *right) { size_t i; vitte_aggregate *out = left != NULL ? left : vitte_aggregate_new(); if (out == NULL) abort(); if (right != NULL) { vitte_aggregate_reserve_items(out, out->count + right->count); for (i = 0u; i < right->count; i++) out->items[out->count++] = right->items[i]; for (i = 0u; i < right->field_count; i++) { vitte_value *field = vitte_aggregate_field(out, right->fields[i].name, true); if (field != NULL) *field = right->fields[i].value; } } return out; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static int64_t vitte_aggregate_unbox_int(vitte_aggregate *value) { return vitte_aggregate_get_field_int(value, \"$value\"); }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static vitte_aggregate *vitte_aggregate_binary_int(vitte_aggregate *left, vitte_aggregate *right, const char *op) { int64_t a = vitte_aggregate_unbox_int(left); int64_t b = vitte_aggregate_unbox_int(right); int64_t result = 0; vitte_aggregate *out = vitte_aggregate_new(); if (strcmp(op, \"+\") == 0) result = a + b; else if (strcmp(op, \"-\") == 0) result = a - b; else if (strcmp(op, \"*\") == 0) result = a * b; else if (strcmp(op, \"/\") == 0) result = b != 0 ? a / b : 0; else if (strcmp(op, \"%\") == 0) result = b != 0 ? a % b : 0; else if (strcmp(op, \"&\") == 0) result = a & b; else if (strcmp(op, \"|\") == 0) result = a | b; else if (strcmp(op, \"^\") == 0) result = a ^ b; else if (strcmp(op, \"<<\") == 0) result = a << b; else if (strcmp(op, \">>\") == 0) result = a >> b; vitte_aggregate_set_field_int(out, \"$value\", result); return out; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#if defined(__GNUC__) || defined(__clang__)");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#define VITTE_C17_USED __attribute__((used))");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#else");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#define VITTE_C17_USED");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#endif");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static const char vitte_bootstrap_compiler_entry_marker[] VITTE_C17_USED = \"COMPILER_ENTRY_POINT=src/vitte/compiler/main.vit\";");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        unit->include_count += 8u;
    }

    return VITTE_STATUS_OK;
}
