#include "translation_unit.h"

#include <string.h>

static void vitte_c17_translation_unit_set_error(
    vitte_c17_translation_unit_t *unit,
    vitte_status_t status,
    const char *code,
    const char *message,
    const char *details
) {
    if (unit != NULL) {
        vitte_error_set_details(&unit->last_error, status, code, message, details);
    }
}

void vitte_c17_translation_unit_init(
    vitte_c17_translation_unit_t *unit,
    const vitte_c17_options_t *options
) {
    if (unit == NULL) {
        return;
    }

    memset(unit, 0, sizeof(*unit));
    vitte_error_init(&unit->last_error);
    if (options != NULL) {
        unit->options = *options;
    } else {
        vitte_c17_options_init(&unit->options);
    }
}

void vitte_c17_translation_unit_reset(vitte_c17_translation_unit_t *unit) {
    if (unit == NULL) {
        return;
    }

    unit->include_count = 0u;
    unit->declaration_count = 0u;
    unit->function_count = 0u;
    vitte_error_reset(&unit->last_error);
}

const vitte_error_t *vitte_c17_translation_unit_last_error(const vitte_c17_translation_unit_t *unit) {
    return unit != NULL ? &unit->last_error : vitte_error_last();
}

vitte_status_t vitte_c17_translation_unit_emit_prelude(
    vitte_c17_translation_unit_t *unit,
    vitte_c17_writer_t *writer
) {
    vitte_status_t status;

    if (unit == NULL || writer == NULL) {
        vitte_c17_translation_unit_set_error(unit, VITTE_STATUS_ERROR_INVALID_ARGUMENT, "VITTE_C17_E_UNIT", "missing C17 translation unit or writer", NULL);
        return VITTE_STATUS_ERROR_INVALID_ARGUMENT;
    }

    if (unit->options.emit_debug_comments) {
        status = vitte_c17_write_string(writer, "/* generated by vitte bootstrap C17 backend */");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
    }

    if (unit->options.emit_includes) {
        status = vitte_c17_write_string(writer, "#include <stdbool.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stdint.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stddef.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stdio.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <stdlib.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <string.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <assert.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "#include <sys/stat.h>");
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) {
            return status;
        }
        status = vitte_c17_write_string(writer, "char *vitte_slice(const char *text, size_t start, size_t end) { size_t length; char *out; if (text == NULL) return NULL; length = strlen(text); if (start > length) start = length; if (end > length) end = length; if (end < start) end = start; out = (char *)malloc(end - start + 1u); if (out == NULL) return NULL; memcpy(out, text + start, end - start); out[end - start] = '\\0'; return out; }");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#if defined(__GNUC__) || defined(__clang__)");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#define VITTE_C17_USED __attribute__((used))");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#else");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#define VITTE_C17_USED");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "#endif");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_string(writer, "static const char vitte_bootstrap_compiler_entry_marker[] VITTE_C17_USED = \"COMPILER_ENTRY_POINT=src/vitte/compiler/main.vit\";");
        if (status != VITTE_STATUS_OK) return status;
        status = vitte_c17_write_newline(writer);
        if (status != VITTE_STATUS_OK) return status;
        unit->include_count += 8u;
    }

    return VITTE_STATUS_OK;
}
