// -----------------------------------------
// Generated by Vitte compiler (C++ backend)
// -----------------------------------------

#include <cstdint>
#include <cstdlib>
#include "vitte_runtime.hpp"
#include <cstddef>

int32_t vitte__b__b();
int32_t vitte__graph__a__a();
extern "C" int32_t vitte__main();
int32_t main(int32_t argc, const char** argv);

int32_t vitte__b__b() {
    bb_0_0:
    return 2;
}

int32_t vitte__graph__a__a() {
    bb_1_0:
    return 1;
}

extern "C" int32_t vitte__main() {
    bb_2_0:
    return 0;
}

int32_t main(int32_t argc, const char** argv) {
    vitte_set_args(argc, argv);
    return vitte__main();
}

