# .clippy.toml — règles de bon goût (et de survie) pour tout le repo

# ===== Version minimale supportée (aligne avec rust-toolchain.toml / CI) =====
msrv = "1.82.0"

# ===== Complexité & lisibilité =====
# On serre un peu les vis pour freiner la dette technique.
cognitive-complexity-threshold = 20      # défaut ≈ 25
too-many-arguments-threshold   = 6       # défaut 7
type-complexity-threshold      = 200     # défaut ≈ 250
too-many-lines-threshold       = 200     # lignes avant warn sur too_many_lines
enum-variant-name-threshold    = 3       # préfixe commun trop verbeux
enum-variant-size-threshold    = 160     # bytes avant warn sur grosses variants

# ===== Docs =====
# Mots techniques acceptés par clippy::doc_markdown (sans backticks)
doc-valid-idents = [
  "API", "ASCII", "CPU", "GPU", "TLS", "SSL", "HTTP", "HTTPS",
  "IPv4", "IPv6", "TCP", "UDP", "URL", "URI", "UUID", "ID",
  "NaN", "Inf", "UTF-8", "UTF-16", "JSON", "XML", "HTML",
  "WASM", "WASI", "SIMD", "I/O", "CLI", "GUI", "FFI", "ABI",
  "ARM", "Cortex-M", "x86_64", "VTOR", "DMA", "ISR", "IRQ",
  "VGA", "PIT", "PIC", "GDT", "IDT",
  "VM", "LSP", "IR", "CFG", "DFG", "VITBC", "JUCE", "OpenGL", "LLVM",
]

# ===== Noms à bannir (clippy::disallowed_names) =====
disallowed-names = [
  "foo", "bar", "baz", "qux", "quux",
  "tmp", "temp", "data", "value", "var",
]

# ===== Interdits ciblés =====
# Alimente : disallowed_types / disallowed_methods / disallowed_macros
[[disallowed-types]]
path = "std::sync::Mutex"
reason = "Préférer parking_lot::Mutex (perfs, pas de poison)."

[[disallowed-types]]
path = "std::sync::RwLock"
reason = "Souvent sur-utilisé ; préférer parking_lot::RwLock ou repenser l’archi."

[[disallowed-methods]]
path = "std::mem::uninitialized"
reason = "UB-land : utiliser core::mem::MaybeUninit."

[[disallowed-methods]]
path = "std::process::Command::output"
reason = "Wrappe avec timeouts, logs et erreurs enrichies (pas brut)."

[[disallowed-macros]]
path = "dbg"
reason = "OK en dev/test, mais pas en prod."

# (Optionnel) Si tu veux aussi encadrer l’IO directe :
# [[disallowed-macros]]
# path = "println!"
# reason = "Utiliser tracing/log ; autorisé en tests via `allow-print-in-tests`."

# ===== Tests : pragmatisme assumé =====
# Ces flags relâchent certains lints dans #[cfg(test)], pas ailleurs.
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests    = true
allow-print-in-tests  = true
