# rustfmt.toml — Vitte workspace (Rust 1.82)
#
# The profile now sticks to the stable rustfmt surface to avoid nightly-only
# warnings during `cargo fmt`. If we decide to opt back into nightly features,
# document it here and in CI.

# ===== Largeurs & heuristiques =====
max_width = 100
use_small_heuristics = "Max"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# ===== Imports =====
reorder_imports = true
reorder_modules = true

# ===== Divers =====
merge_derives = true
edition = "2024"
