// -----------------------------------------
// Generated by Vitte compiler (C++ backend)
// -----------------------------------------

#include "cstdint"
#include "cstddef"
#include "vitte_runtime.hpp"
#include <cstdint>
#include <cstddef>

extern void kernel_console_write_byte(uint8_t b);

extern int32_t kernel_console_read_key();

extern void kernel_yield();

extern uint64_t kernel_ticks();

extern uint64_t kernel_syscall(uint64_t n, uint64_t a0, uint64_t a1, uint64_t a2, uint64_t a3, uint64_t a4, uint64_t a5);

void vitte__console_write_byte(uint8_t b) {
    bb_5_0:
    kernel_console_write_byte(b);
    return;
}

int32_t vitte__console_read_key() {
    int32_t _t0;
    bb_6_0:
    _t0 = kernel_console_read_key();
    return _t0;
}

void vitte__task_yield() {
    bb_7_0:
    kernel_yield();
    return;
}

void vitte__syscall_write_byte(uint8_t b) {
    int32_t _;
    uint64_t _t0;
    bb_8_0:
    _t0 = kernel_syscall(0, b, 0, 0, 0, 0, 0);
    _ = _t0;
    return;
}

int32_t vitte__syscall_read_key() {
    uint64_t _t0;
    bb_9_0:
    _t0 = kernel_syscall(1, 0, 0, 0, 0, 0, 0);
    return _t0;
}

void vitte__syscall_yield() {
    int32_t _;
    uint64_t _t0;
    bb_10_0:
    _t0 = kernel_syscall(2, 0, 0, 0, 0, 0, 0);
    _ = _t0;
    return;
}

uint64_t vitte__syscall_ticks() {
    uint64_t _t0;
    bb_11_0:
    _t0 = kernel_syscall(3, 0, 0, 0, 0, 0, 0);
    return _t0;
}

void vitte__user_main() {
    int32_t last;
    uint64_t _t0;
    int32_t k;
    int32_t _t1;
    bool _t2;
    bool _t3;
    bool _t4;
    int32_t now;
    uint64_t _t5;
    int32_t _t6;
    bool _t7;
    int32_t _t8;
    bb_12_0:
    vitte__syscall_write_byte(117);
    vitte__syscall_write_byte(115);
    vitte__syscall_write_byte(101);
    vitte__syscall_write_byte(114);
    vitte__syscall_write_byte(62);
    vitte__syscall_write_byte(32);
    _t0 = vitte__syscall_ticks();
    last = _t0;
    goto bb_12_1;
    bb_12_1:
    _t1 = vitte__syscall_read_key();
    k = _t1;
    _t2 = (k >= 0);
    if (_t2) {
        goto bb_12_3;
    } else {
        goto bb_12_4;
    }
    bb_12_2:
    return;
    bb_12_3:
    _t3 = (k == 13);
    if (_t3) {
        goto bb_12_6;
    } else {
        goto bb_12_7;
    }
    bb_12_4:
    goto bb_12_5;
    bb_12_5:
    _t5 = vitte__syscall_ticks();
    now = _t5;
    _t6 = (now - last);
    _t7 = (_t6 >= 100);
    if (_t7) {
        goto bb_12_12;
    } else {
        goto bb_12_13;
    }
    bb_12_6:
    vitte__syscall_write_byte(13);
    vitte__syscall_write_byte(10);
    vitte__syscall_write_byte(62);
    vitte__syscall_write_byte(32);
    goto bb_12_8;
    bb_12_7:
    _t4 = (k == 8);
    if (_t4) {
        goto bb_12_9;
    } else {
        goto bb_12_10;
    }
    bb_12_8:
    goto bb_12_5;
    bb_12_9:
    vitte__syscall_write_byte(8);
    vitte__syscall_write_byte(32);
    vitte__syscall_write_byte(8);
    goto bb_12_11;
    bb_12_10:
    vitte__syscall_write_byte(k);
    goto bb_12_11;
    bb_12_11:
    goto bb_12_8;
    bb_12_12:
    vitte__syscall_write_byte(46);
    _t8 = (last + now);
    goto bb_12_14;
    bb_12_13:
    goto bb_12_14;
    bb_12_14:
    vitte__syscall_yield();
    goto bb_12_1;
}

int32_t vitte__main() {
    bb_13_0:
    vitte__console_write_byte(75);
    vitte__console_write_byte(58);
    vitte__console_write_byte(32);
    vitte__console_write_byte(117);
    vitte__console_write_byte(115);
    vitte__console_write_byte(101);
    vitte__console_write_byte(114);
    vitte__console_write_byte(10);
    vitte__user_main();
    goto bb_13_1;
    bb_13_1:
    vitte__task_yield();
    goto bb_13_1;
    bb_13_2:
    return 0;
}

