/*
 *	Sydney C Compiler.
 *
 *	Copyright 1984, Bruce Ellis.
 *
 *	Unauthorised possesion, sale or use prohibited.
 */

#include	"defs.h"

tkdope	tkdopes[] =
{
/*&*/		{pack(xt_and),		5},
/*&&*/		{pack(xt_andand),	2},
/*auto*/	{pack(xt_null),		-1},
/*|*/		{pack(xt_bar),		3},
/*||*/		{pack(xt_barbar),	1},
/*break*/	{pack(xt_null),		-1},
/*case*/	{pack(xt_null),		-1},
/*const char*/	{pack(xt_cchar),	-1},
/*const doub*/	{pack(xt_cdouble),	-1},
/*const float*/	{pack(xt_cfloat),	-1},
/*char*/	{pack(xt_null),		-1},
/*const int*/	{pack(xt_cint),		-1},
/*const long*/	{pack(xt_clong),	-1},
/*:*/		{pack(xt_colon),	-1},
/*,*/		{pack(xt_comma),	-1},
/*continue*/	{pack(xt_null),		-1},
/*default*/	{pack(xt_null),		-1},
/*do*/		{pack(xt_null),		-1},
/*.*/		{pack(xt_null),		-1},
/*double*/	{pack(xt_null),		-1},
/*else*/	{pack(xt_null),		-1},
/*enum*/	{pack(xt_null),		-1},
/*eof*/		{pack(xt_null),		-1},
/*=*/		{pack(xt_eq),		0},
/*==*/		{pack(xt_eqeq),		6},
/*extern*/	{pack(xt_null),		-1},
/*float*/	{pack(xt_null),		-1},
/*for*/		{pack(xt_null),		-1},
/*goto*/	{pack(xt_null),		-1},
/*>*/		{pack(xt_grt),		7},
/*>=*/		{pack(xt_grteq),	7},
/*>>*/		{pack(xt_grtgrt),	8},
/*if*/		{pack(xt_null),		-1},
/*int*/		{pack(xt_null),		-1},
/*<*/		{pack(xt_less),		7},
/*<=*/		{pack(xt_lesseq),	7},
/*<<*/		{pack(xt_lessless),	8},
/*<-*/		{pack(xt_null),		-1},
/*long*/	{pack(xt_null),		-1},
/*maxof*/	{pack(xt_maxof),	-1},
/*minof*/	{pack(xt_minof),	-1},
/*-*/		{pack(xt_minus),	9},
/*->*/		{pack(xt_null),		-1},
/*--*/		{pack(xt_predec),	-1},
/*name*/	{pack(xt_null),		-1},
/*!*/		{pack(xt_not),		-1},
/*!=*/		{pack(xt_noteq),	6},
/*null*/	{pack(xt_null),		-1},
/*}*/		{pack(xt_null),		-1},
/*)*/		{pack(xt_null),		-1},
/*]*/		{pack(xt_null),		-1},
/*{*/		{pack(xt_null),		-1},
/*(*/		{pack(xt_null),		-1},
/*[*/		{pack(xt_null),		-1},
/*%*/		{pack(xt_percent),	10},
/*+*/		{pack(xt_plus),		9},
/*++*/		{pack(xt_preinc),	-1},
/*?*/		{pack(xt_question),	-1},
/*register*/	{pack(xt_null),		-1},
/*return*/	{pack(xt_null),		-1},
/*;*/		{pack(xt_null),		-1},
/*set*/		{pack(xt_null),		-1},
/*short*/	{pack(xt_null),		-1},
/*sizeof*/	{pack(xt_sizeof),	-1},
/*/*/		{pack(xt_slash),	10},
/*static*/	{pack(xt_null),		-1},
/*struct*/	{pack(xt_null),		-1},
/*".."*/	{pack(xt_string),	-1},
/*switch*/	{pack(xt_null),		-1},
/*~*/		{pack(xt_tilda),	-1},
/***/		{pack(xt_times),	10},
/*typedef*/	{pack(xt_null),		-1},
/*union*/	{pack(xt_null),		-1},
/*unsigned*/	{pack(xt_null),		-1},
/*^*/		{pack(xt_uparrow),	4},
/*while*/	{pack(xt_null),		-1},
};

char	*where_name[] =
{
	"external declaration",
	"argument",
	"block",
	"cast",
	"enum",
	"struct",
	"union",
	"junk",
};

