#!/bin/sh
set -p
PATH=/bin:/usr/bin
export PATH
umask 22
case $# in
0)	echo nothing to ship
	exit 1
esac
spool=`/usr/lib/asd/mkspool`
T=$spool/`date -n`
trap "rm -f $T.t $T.d $T.s; exit 1" 1 2 3 15
(	echo '#' `date` "$@"
	case "$dest" in
	"")	egrep -v /`cat /etc/whoami`\$ /usr/lib/asd/destinations
		;;
	*)	for i in $dest
		do	echo "# dest:" $i
		done
		for i in $dest
		do	echo $i
		done
		;;
	esac
) >$T.t
grep '^#' $T.t | /bin/mail bowell!rootasd
mkpkg "$@" >$T.d
mv $T.t $T.s
rm -f $spool/dummy
trap '' 1 2 3 15
/usr/lib/asd/udaemon </dev/null >/dev/null 2>/dev/null 3>/dev/null &
