MFLOWS=atomic.u europa.u fs.u trevor.u
COMETS=dolphy.u most.u
STARS=cbdkc3.u
MFAIRS=bartok.u
all:V:$MFLOWS $COMETS $STARS $MFAIRS
$MFLOWS:V:
	mk -f ../lib/mk.mflow $target
$COMETS:V:
	mk -f ../lib/mk.comet $target
$STARS:V:
	mk -f ../lib/mk.star $target
$MFAIRS:V:
	mk -f ../lib/mk.mfair $target
