[package]
name         = "vitte-resolve"
description  = "Résolution déterministe des dépendances pour Vitte (semver, graphe, provider abstrait)."
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
documentation = "https://docs.rs/vitte-resolve"

keywords   = ["dependency", "resolver", "semver", "graph", "package"]
categories = ["development-tools", "build-tools", "algorithms"]

[lib]
name = "vitte_resolve"
path = "lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std     = []

[dependencies]
semver    = "1.0"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "1.4"

[package.metadata.docs.rs]
all-features        = false
features            = ["std"]
no-default-features = false
rustdoc-args        = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all      = "warn"
pedantic = "warn"
