#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "target" / "llvm_native_final"
REPORT_DIR = ROOT / "target" / "reports"
SOURCE = ROOT / "tests" / "bootstrap_native" / "main_proc.vit"

NATIVE_IR = OUT_DIR / "main.native_ir"
LLVM_IR = OUT_DIR / "main.ll"
LLVM_BC = OUT_DIR / "main.bc"
OBJECT = OUT_DIR / "main.o"
EXECUTABLE = OUT_DIR / "main"
REPORT_JSON = REPORT_DIR / "llvm_native_final_gate.json"
REPORT_MD = REPORT_DIR / "llvm_native_final_gate.md"


def run(cmd: list[str], *, check: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=check,
    )


def write_report(status: str, steps: list[dict[str, object]], details: dict[str, object]) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report = {
        "version": "v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "backend": "llvm",
        "gate": "llvm-native-final",
        "status": status,
        "source": str(SOURCE.relative_to(ROOT)),
        "artifacts": {
            "native_ir": str(NATIVE_IR.relative_to(ROOT)),
            "llvm_ir": str(LLVM_IR.relative_to(ROOT)),
            "bitcode": str(LLVM_BC.relative_to(ROOT)) if LLVM_BC.exists() else "",
            "object": str(OBJECT.relative_to(ROOT)) if OBJECT.exists() else "",
            "executable": str(EXECUTABLE.relative_to(ROOT)) if EXECUTABLE.exists() else "",
        },
        "details": details,
        "steps": steps,
    }
    REPORT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    lines = [
        "# LLVM Native Final Gate",
        "",
        f"- Status: **{status}**",
        f"- Source: `{SOURCE.relative_to(ROOT)}`",
        f"- LLVM IR: `{LLVM_IR.relative_to(ROOT)}`",
        f"- Object: `{OBJECT.relative_to(ROOT) if OBJECT.exists() else ''}`",
        f"- Executable: `{EXECUTABLE.relative_to(ROOT) if EXECUTABLE.exists() else ''}`",
        "",
        "## Steps",
        "",
        "| Step | Status | Detail |",
        "| --- | --- | --- |",
    ]
    for step in steps:
        lines.append(f"| {step['name']} | {step['status']} | {step.get('detail', '')} |")
    lines.append("")
    REPORT_MD.write_text("\n".join(lines), encoding="utf-8")


def parse_native_ir(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in text.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def lower_native_ir_to_llvm(values: dict[str, str]) -> str:
    main_return = int(values.get("main.return", "0"))
    if main_return < 0 or main_return > 255:
        raise ValueError(f"main.return outside portable process status range: {main_return}")
    return "\n".join(
        [
            "; LLVM IR generated by llvm-native-final-gate from Vitte native_ir_v1",
            f'; source = "{SOURCE.relative_to(ROOT)}"',
            f"; version_text = {values.get('version_text', '')}",
            f"; banner_text = {values.get('banner_text', '')}",
            'source_filename = "tests/bootstrap_native/main_proc.vit"',
            "",
            "define i32 @main(i32 %argc, ptr %argv) {",
            "entry:",
            f"  ret i32 {main_return}",
            "}",
            "",
        ]
    )


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    required = os.environ.get("VITTE_LLVM_NATIVE_FINAL_REQUIRED") == "1"
    strict_llvm_as = os.environ.get("VITTE_LLVM_NATIVE_FINAL_STRICT_LLVM_AS") == "1"

    clang = shutil.which("clang")
    llvm_as = shutil.which("llvm-as")
    steps: list[dict[str, object]] = []

    if not clang:
        status = "FAIL" if required else "SKIP"
        detail = "clang not found"
        steps.append({"name": "toolchain", "status": status, "detail": detail})
        write_report(status, steps, {"required": required, "clang": "", "llvm_as": llvm_as or ""})
        print(f"[llvm-native-final] {status.lower()}: {detail}")
        return 1 if required else 0

    if strict_llvm_as and not llvm_as:
        steps.append({"name": "toolchain", "status": "FAIL", "detail": "llvm-as not found"})
        write_report("FAIL", steps, {"required": required, "clang": clang, "llvm_as": ""})
        print("[llvm-native-final][error] llvm-as not found")
        return 1

    native = run(["bin/vitte", "dump-native-ir", "--src", str(SOURCE.relative_to(ROOT))])
    NATIVE_IR.write_text(native.stdout, encoding="utf-8")
    if native.returncode != 0:
        steps.append({"name": "vitte-to-native-ir", "status": "FAIL", "detail": native.stderr.strip()})
        write_report("FAIL", steps, {"clang": clang, "llvm_as": llvm_as or ""})
        print("[llvm-native-final][error] Vitte native IR emission failed")
        return 1
    steps.append({"name": "vitte-to-native-ir", "status": "PASS", "detail": str(NATIVE_IR.relative_to(ROOT))})

    try:
        values = parse_native_ir(native.stdout)
        llvm_text = lower_native_ir_to_llvm(values)
    except Exception as exc:
        steps.append({"name": "native-ir-to-llvm-ir", "status": "FAIL", "detail": str(exc)})
        write_report("FAIL", steps, {"clang": clang, "llvm_as": llvm_as or ""})
        print(f"[llvm-native-final][error] {exc}")
        return 1
    LLVM_IR.write_text(llvm_text, encoding="utf-8")
    steps.append({"name": "native-ir-to-llvm-ir", "status": "PASS", "detail": str(LLVM_IR.relative_to(ROOT))})

    if llvm_as:
        bitcode = run([llvm_as, str(LLVM_IR), "-o", str(LLVM_BC)])
        if bitcode.returncode != 0:
            steps.append({"name": "llvm-as", "status": "FAIL", "detail": bitcode.stderr.strip()})
            write_report("FAIL", steps, {"clang": clang, "llvm_as": llvm_as})
            print("[llvm-native-final][error] llvm-as failed")
            return 1
        steps.append({"name": "llvm-as", "status": "PASS", "detail": str(LLVM_BC.relative_to(ROOT))})
    else:
        steps.append({"name": "llvm-as", "status": "SKIP", "detail": "llvm-as not found; clang will consume .ll directly"})

    compile_obj = run([clang, "-Wno-override-module", "-c", str(LLVM_IR), "-o", str(OBJECT)])
    if compile_obj.returncode != 0 or not OBJECT.exists() or OBJECT.stat().st_size == 0:
        steps.append({"name": "clang-object", "status": "FAIL", "detail": compile_obj.stderr.strip()})
        write_report("FAIL", steps, {"clang": clang, "llvm_as": llvm_as or ""})
        print("[llvm-native-final][error] clang object emission failed")
        return 1
    steps.append({"name": "clang-object", "status": "PASS", "detail": str(OBJECT.relative_to(ROOT))})

    link = run([clang, str(OBJECT), "-o", str(EXECUTABLE)])
    if link.returncode != 0 or not EXECUTABLE.exists():
        steps.append({"name": "clang-link", "status": "FAIL", "detail": link.stderr.strip()})
        write_report("FAIL", steps, {"clang": clang, "llvm_as": llvm_as or ""})
        print("[llvm-native-final][error] clang link failed")
        return 1
    steps.append({"name": "clang-link", "status": "PASS", "detail": str(EXECUTABLE.relative_to(ROOT))})

    executed = run([str(EXECUTABLE)])
    expected = int(parse_native_ir(native.stdout).get("main.return", "0"))
    if executed.returncode != expected:
        steps.append({"name": "run", "status": "FAIL", "detail": f"expected {expected}, got {executed.returncode}"})
        write_report("FAIL", steps, {"clang": clang, "llvm_as": llvm_as or ""})
        print(f"[llvm-native-final][error] run returned {executed.returncode}, expected {expected}")
        return 1
    steps.append({"name": "run", "status": "PASS", "detail": f"exit={executed.returncode}"})

    write_report("PASS", steps, {"clang": clang, "llvm_as": llvm_as or "", "expected_exit": expected})
    print(
        "[llvm-native-final] "
        "vitte_ir=PASS llvm_ir=PASS object=PASS link=PASS run=PASS "
        f"exit={expected}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
