// -----------------------------------------
// Generated by Vitte compiler (C++ backend)
// -----------------------------------------

#include <cstdint>
#include <cstdlib>
#include "vitte_runtime.hpp"
#include <cstddef>

builtin.i32 vitte__add(builtin.i32 a, builtin.i32 b);
extern "C" builtin.i32 vitte__main();
int32_t main(int32_t argc, const char** argv);

builtin.i32 vitte__add(builtin.i32 a, builtin.i32 b) {
    int32_t _t0;
    bb_0_0:
    _t0 = (a + b);
    return _t0;
}

extern "C" builtin.i32 vitte__main() {
    builtin.i32 _t0;
    builtin.i32 total;
    bool _t1;
    bb_1_0:
    _t0 = vitte__add(20, 22);
    total = _t0;
    _t1 = (total == 42);
    if (_t1) {
        goto bb_1_1;
    } else {
        goto bb_1_2;
    }
    bb_1_1:
    return 0;
    bb_1_2:
    goto bb_1_3;
    bb_1_3:
    return 1;
}

int32_t main(int32_t argc, const char** argv) {
    vitte_set_args(argc, argv);
    return vitte__main();
}

