[package]
name        = "vitte-repl"
description = "REPL interactif pour le langage Vitte (lecture, évaluation, impression)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-repl"

keywords   = ["compiler", "repl", "interactive", "vitte"]
categories = ["compilers", "development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[[bin]]
name = "vitte-repl"
path = "src/main.rs"

[lib]
name = "vitte_repl"
path = "src/lib.rs"

[features]
default = ["std"]
std     = []

[dependencies]
vitte-compiler = { path = "../vitte-compiler" }
vitte-errors   = { path = "../vitte-errors" }
vitte-ir       = { path = "../vitte-ir" }

anyhow        = "1.0"
thiserror     = "1.0"
rustyline     = "14.0"
dirs          = { version = "5.0", optional = true }
nu-ansi-term  = { version = "0.50", optional = true }

serde      = { workspace = true, features = ["derive"] }
serde_json = "1.0"
tungstenite = { version = "0.21", features = ["rustls-tls-native-roots"] }
url = "2.5"

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = "3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
doc_markdown            = "allow"
too_many_lines          = "allow"
