#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
MANIFEST = ROOT / "toolchain" / "scripts" / "interop" / "vitte_c_abi_v1.json"
OUT_INCLUDE = ROOT / "target" / "interop" / "include" / "vitte"
OUT_C = OUT_INCLUDE / "vitte_abi.h"
OUT_CPP = OUT_INCLUDE / "vitte_abi.hpp"
OUT_EXPORTS = ROOT / "target" / "interop" / "vitte_c_abi_exports_v1.txt"
SNAPSHOT = ROOT / "tests" / "interop" / "abi" / "vitte_c_abi_exports_v1.must"


def fmt_params(params: list[dict[str, str]]) -> str:
    if not params:
        return "void"
    return ", ".join(f"{p['type']} {p['name']}" for p in params)


def render_c_header(spec: dict) -> str:
    lines: list[str] = []
    lines.append("/* Auto-generated by toolchain/scripts/interop/generate_interop_headers.py */")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    for m in spec["macros"]:
        lines.append(f"#define {m['name']} {m['value']}")
    lines.append("")
    for t in spec["types"]:
        lines.append("typedef struct " + t["name"] + " {")
        for f in t["fields"]:
            lines.append(f"  {f['type']} {f['name']};")
        lines.append("} " + t["name"] + ";")
        lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    for fn in spec["functions"]:
        lines.append(f"{fn['ret']} {fn['name']}({fmt_params(fn['params'])});")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def render_cpp_header(spec: dict) -> str:
    lines: list[str] = []
    lines.append("// Auto-generated by toolchain/scripts/interop/generate_interop_headers.py")
    lines.append("#pragma once")
    lines.append('#include "vitte_abi.h"')
    lines.append("")
    lines.append("namespace vitte::interop {")
    lines.append(f'inline constexpr const char* kCAbiVersion = "{spec["version"]}";')
    lines.append("")
    for fn in spec["functions"]:
        params = ", ".join(f"{p['type']} {p['name']}" for p in fn["params"])
        args = ", ".join(p["name"] for p in fn["params"])
        lines.append(f"inline {fn['ret']} {fn['name']}({params}) {{")
        lines.append(f"  return ::{fn['name']}({args});" if fn["ret"] != "void" else f"  ::{fn['name']}({args});")
        lines.append("}")
        lines.append("")
    lines.append("} // namespace vitte::interop")
    lines.append("")
    return "\n".join(lines)


def render_exports(spec: dict) -> str:
    names = sorted(fn["name"] for fn in spec["functions"])
    return "\n".join(names) + "\n"


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate interop C/C++ ABI headers and export snapshots")
    ap.add_argument("--check", action="store_true", help="fail if generated files differ from current files")
    ap.add_argument("--update-snapshot", action="store_true", help="update tests/interop snapshot from manifest")
    args = ap.parse_args()

    spec = json.loads(MANIFEST.read_text(encoding="utf-8"))
    c_text = render_c_header(spec)
    cpp_text = render_cpp_header(spec)
    exports_text = render_exports(spec)

    if args.check:
        expected = {
            OUT_C: c_text,
            OUT_CPP: cpp_text,
            OUT_EXPORTS: exports_text,
        }
        if SNAPSHOT.exists():
            expected[SNAPSHOT] = exports_text
        dirty = []
        for p, e in expected.items():
            cur = p.read_text(encoding="utf-8") if p.exists() else None
            if cur != e:
                dirty.append(str(p))
        if dirty:
            for p in dirty:
                print(f"[interop-headers][error] out of date: {p}")
            return 1
        print("[interop-headers] OK")
        return 0

    changed = []
    if write_if_changed(OUT_C, c_text):
        changed.append(str(OUT_C))
    if write_if_changed(OUT_CPP, cpp_text):
        changed.append(str(OUT_CPP))
    if write_if_changed(OUT_EXPORTS, exports_text):
        changed.append(str(OUT_EXPORTS))
    if args.update_snapshot and write_if_changed(SNAPSHOT, exports_text):
        changed.append(str(SNAPSHOT))
    for p in changed:
        print(f"[interop-headers] wrote {p}")
    if not changed:
        print("[interop-headers] up-to-date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
