#!/bin/sh
# mount v7 and v6 system disk images
nohup ./runfs v5 f6 v5disk >/dev/null 2>&1 3>&1 &
nohup ./runfs v6/bin f6 v6bin >/dev/null 2>&1 3>&1 &
nohup ./runfs v6/doc f6 v6doc >/dev/null 2>&1 3>&1 &
nohup ./runfs v6/src f6 v6src >/dev/null 2>&1 3>&1 &
