#
# 1127 systems
#

all:V: jak.u

x.u:V:
	mk  -f ../lib/mk.comet $target
jak.u:V:
	mk  -f ../lib/mk.comet $target
lccjak.u:V:
	mk  -f ../lib/lccmk.comet $target
#	cp jak.u jak1.u
#	echo 'rootdev?w0x748;swdevt?w0x709' | adb -w jak1.u
#	cp jak.u horse.u
#	echo 'uzero?w0xff;tzero?w0xff;tzero0?w0xff' | adb -w horse.u
install:V:	jak.u
	cp jak.u /x0
	cp jak1.u /x1
	cp horse.u /horse
