what:
		@echo "what do you want to make?"

Dist-clean:
		rm -f *.*K* .emacs*
		rm -f `gcomp Makefile`

Dist-unix:
		rm -rf pc_dos vax_vms work

Dist-vms:
		rm -rf `gcomp vax_vms`

Dist-dos:	rm -rf `gcomp pc_dos`
