
# CI Coverage workflow for fuzz targets (C17) + optional sanitizer run.
# Notes:
# - Designed for GitHub Actions.
# - Produces LCOV + HTML report artifacts.
# - Uploads to Codecov if CODECOV_TOKEN secret is available.
# - Keeps commands conservative and portable.

name: coverage

on:
  push:
    paths:
      - "fuzz/**"
      - "compiler/**"
      - "runtime/**"
      - "include/**"
      - "tools/**"
      - "CMakeLists.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "fuzz/**"
      - "compiler/**"
      - "runtime/**"
      - "include/**"
      - "tools/**"
      - "CMakeLists.txt"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_DIR: build-coverage
  CMAKE_BUILD_TYPE: Debug
  # Coverage flags for clang/gcc
  COV_CFLAGS: "-O0 -g --coverage -fprofile-arcs -ftest-coverage -fno-inline -fno-omit-frame-pointer"
  COV_LDFLAGS: "--coverage"

jobs:
  linux-coverage:
    name: Linux coverage (clang)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake ninja-build clang lld \
            lcov gcovr \
            python3 python3-pip \
            zip

      - name: Configure (coverage)
        run: |
          cmake -S . -B "${BUILD_DIR}" -G Ninja \
            -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_C_FLAGS="${COV_CFLAGS}" \
            -DCMAKE_EXE_LINKER_FLAGS="${COV_LDFLAGS}" \
            -DCMAKE_SHARED_LINKER_FLAGS="${COV_LDFLAGS}" \
            -DCMAKE_MODULE_LINKER_FLAGS="${COV_LDFLAGS}"

      - name: Build
        run: |
          cmake --build "${BUILD_DIR}" --config "${CMAKE_BUILD_TYPE}"

      - name: Zero counters
        run: |
          lcov --directory "${BUILD_DIR}" --zerocounters || true

      - name: Run unit tests (if any)
        run: |
          ctest --test-dir "${BUILD_DIR}" --output-on-failure || true

      - name: Run fuzz smoke (optional)
        env:
          # Set FUZZ_SMOKE=1 to enable in repo/PR variables.
          FUZZ_SMOKE: ${{ vars.FUZZ_SMOKE }}
          # Optional: limit runtime
          FUZZ_SECONDS: ${{ vars.FUZZ_SECONDS }}
        run: |
          if [ "${FUZZ_SMOKE}" = "1" ]; then
            echo "FUZZ_SMOKE enabled"
            SECS="${FUZZ_SECONDS:-15}"
            # If you have a dedicated runner script, prefer it:
            #   tools/scripts/fuzz_smoke.sh "${BUILD_DIR}" "${SECS}"
            #
            # Otherwise run common libFuzzer style binaries found in build.
            mapfile -t FUZZERS < <(find "${BUILD_DIR}" -type f -maxdepth 4 -name "*fuzz*" -perm -111 2>/dev/null || true)
            if [ "${#FUZZERS[@]}" -eq 0 ]; then
              echo "No fuzzers found; skipping."
              exit 0
            fi
            for f in "${FUZZERS[@]}"; do
              echo "Run: ${f}"
              "${f}" -runs=2000 -max_total_time="${SECS}" || true
            done
          else
            echo "FUZZ_SMOKE disabled (set repository variable FUZZ_SMOKE=1 to enable)."
          fi

      - name: Capture lcov
        run: |
          mkdir -p coverage
          lcov --capture --directory "${BUILD_DIR}" --output-file coverage/lcov.raw.info

      - name: Filter lcov (remove system + external)
        run: |
          # Adjust exclude patterns to your tree.
          lcov --remove coverage/lcov.raw.info \
            "/usr/*" \
            "*/_deps/*" \
            "*/third_party/*" \
            "*/external/*" \
            "*/build/*" \
            --output-file coverage/lcov.info

      - name: Generate HTML
        run: |
          genhtml coverage/lcov.info --output-directory coverage/html

      - name: Coverage summary
        run: |
          lcov --summary coverage/lcov.info || true

      - name: Upload artifacts (lcov + html)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-linux
          path: |
            coverage/lcov.info
            coverage/html
          if-no-files-found: warn
          retention-days: 14

      - name: Upload to Codecov (optional)
        if: ${{ secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: linux,coverage
          fail_ci_if_error: false

  linux-asan-smoke:
    name: Linux ASan smoke (clang)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.event_name != 'pull_request' || vars.ASAN_SMOKE_PR == '1' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake ninja-build clang lld \
            python3

      - name: Configure (ASan)
        run: |
          cmake -S . -B build-asan -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_C_FLAGS="-O1 -g -fsanitize=address,undefined -fno-omit-frame-pointer" \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address,undefined"

      - name: Build
        run: |
          cmake --build build-asan --config Debug

      - name: Run tests (best effort)
        run: |
          ctest --test-dir build-asan --output-on-failure || true
