#
# 1127 systems
#
COMETS=arend.u dutoit.u encke.u research.u seki.u \
	west.u westphal.u wild.u ssor.u
NAUTS=coma.u bowell.u pipe.u
STARS=alice.u
MFLOWS=kwee.u
MFAIRS=r70.u

all:V: $NAUTS $COMETS $MFLOWS $STARS

$COMETS:V:
	mk -f ../lib/mk.comet $target
$NAUTS:V:
	mk -f ../lib/mk.naut $target
$MFLOWS:V:
	mk -f ../lib/mk.mflow $target
$STARS:V:
	mk -f ../lib/mk.star $target
$MFAIRS:V:
	mk -f ../lib/mk.mfair $target
