.TH PCOPY 1
.SH NAME
pcopy \- paranoid file copy
.SH SYNOPSIS
[
.B priv
]
.B pcopy
[
.I input output
]
.SH DESCRIPTION
.I Pcopy
copies an input file to an output file preserving,
if possible, file ownership, dates, and label.
The copying is performed in
such a way as to assure faithfulness
even in the presence of interfering processes.
.PP
Privilege, obtained via
.IR priv (1),
is required to reproduce privileged files.
The user must be able to write the output file,
and be able to read and write files with the label
of the input file.
.SH SEE ALSO
.IR cp (1),
.IR pex (4)
