#include "steel/compiler/backend_c.h"
#include <stdio.h>

int backend_c_emit_program(const ast_program* prog, const char* out_c_path) {
  (void)prog;
  FILE* f = fopen(out_c_path, "wb");
  if (!f) return -1;

  /* Minimal C translation unit */
  fprintf(f, "/* generated by steelc (scaffold) */\n");
  fprintf(f, "#include <stdint.h>\n");
  fprintf(f, "int main(int argc, char** argv){(void)argc;(void)argv;return %lld;}\n",
          (long long)prog->main_fn.ret.ret_value.value);

  fclose(f);
  return 0;
}
