#define RootPath "/users/icon/v6"
#define IcontPath "/users/icon/v6/bin/icont"
#define LinkPath "/users/icon/v6/bin/ilink"
#define TranPath "/users/icon/v6/bin/itran"
#define IconxPath "/users/icon/v6/bin/iconx"
#define HeaderPath "/users/icon/v6/bin/iconx.hdr"
