[package]
name        = "vitte-unify"
description = "Unificateur de types pour l’écosystème Vitte."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-unify"

keywords   = ["types", "unification", "compiler", "vitte"]
categories = ["development-tools", "compilers"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_unify"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = []

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
doc_markdown            = "allow"
too_many_lines          = "allow"
