#!/bin/sh
# interim security treatment for backup scheme
# backups override standard checks, but themselves get no
# special protection
#
B=/usr/lib/backup
L="$B/fcheck $B/fmpush $B/iprint $B/missing"
/etc/priv setpriv 0 0 $L
