.TH SRC 5
.SH NAME
src \- form of a stream identifier
.SH DESCRIPTION
Stream identifiers, defined in
.IR stream (4),
are conventionally set by
.IR init (8)
and
.IR dkmgr (8)
to designate the source of the login stream.
A datakit source begins with
.B dk!
followed by a dial string.
.PP
.IR Session (1)
may append to the stream identifier of the
standard input a colon and a name,
which is understood by
.IR pwserv (8)
as an assertion that the agent on that stream
knows the password associated with that name,
which obviates further demands for that password.
.SH EXAMPLES
.B dk!201/mu/attbl:doug 
.SH SEE ALSO
.IR getstsrc (3)
