// Generated by tools/repro_generate_cpp.sh
// DO NOT EDIT BY HAND
#include <cstdint>
#include <cstdlib>
#include "vitte_runtime.hpp"
#include <cstddef>

extern "C" int32_t vitte__main() {
    bool _t0;
    int32_t x;
    bb_0_0:
    x = 3;
    _t0 = (x == 3);
    if (_t0) {
        goto bb_0_1;
    } else {
        goto bb_0_2;
    }
    bb_0_1:
    return 7;
    bb_0_2:
    goto bb_0_3;
    bb_0_3:
    return 9;
}

int32_t main(int32_t argc, const char** argv) {
    vitte_set_args(argc, argv);
    return vitte__main();
}


