// Generated by tools/repro_generate_cpp.sh
// DO NOT EDIT BY HAND
#include <cstdint>
#include <cstdlib>
#include "vitte_runtime.hpp"
#include <cstddef>

extern "C" int32_t vitte__main() {
    int32_t _t0;
    int32_t x;
    int32_t y;
    bb_0_0:
    x = 40;
    y = 2;
    _t0 = (x + y);
    return _t0;
}

int32_t main(int32_t argc, const char** argv) {
    vitte_set_args(argc, argv);
    return vitte__main();
}


