char *helpstrs[] = {
	"CAPACITY drive",
	"COPY sdrive sstart nblocks ddrive dstart",
	"DIAGNOSTIC drive",
	"DISK EJECT drive",
	"DISK RELEASE drive shelf side",
	"DISK RELEASE drive",
	"DISK SET shelf side drive",
	"ECHO NUMBER",
	"HELP",
	"ID drive",
	"INQUIRY",
	"INQUIRY drive",
	"MEDIA drive NUMBER NUMBER",
	"MEDIA drive start nblocks \"filename\"",
	"EXT MEDIA drive NUMBER NUMBER",
	"READ drive NUMBER",
	"READ ID drive",
	"RESET",
	"SENSE drive",
	"EXT SENSE drive",
	"SLEEP NUMBER",
	"START drive",
	"STATUS drive",
	"STATUS",
	"STOP drive",
	"WORM drive",
	"WORM drive start",
	"WRITE drive NUMBER",
	"WRITE drive start n",
	0
};
