muf_file          ::= WS? header NL { WS? toplevel WS? NL } WS? EOF ;

header            ::= "muf" WS1 muf_version ;
muf_version       ::= int_lit ;                  # ex: 1

toplevel          ::= workspace_block
                    | package_block
                    | target_block
                    | deps_block
                    | profile_block
                    | toolchain_block
                    | features_block
                    | scripts_block
                    | abi_block
                    | include_block
                    | env_block
                    | on_block
                    ;
                    
                    NL                ::= "\n" | "\r\n" ;

WS                ::= { " " | "\t" | comment | NL } ;
WS1               ::= ( " " | "\t" ) { " " | "\t" } ;

comment           ::= "#" { not_nl } ;

ident             ::= ident_start { ident_continue } ;
ident_start       ::= "A".."Z" | "a".."z" | "_" ;
ident_continue    ::= ident_start | "0".."9" | "-" ;

string_lit        ::= "\"" { string_char } "\"" ;
string_char       ::= "\\\"" | "\\\\" | "\\n" | "\\r" | "\\t" | not_quote_not_nl ;

bool_lit          ::= "true" | "false" ;

int_lit           ::= ["-"] digit { digit }
                    | "0x" hex { hex } ;

float_lit         ::= ["-"] digit { digit } "." digit { digit } ;

digit             ::= "0".."9" ;
hex               ::= digit | "a".."f" | "A".."F" ;

path_lit          ::= string_lit ;              # chemins = string, pas d’atom spécial
semver_lit        ::= string_lit ;              # ex: "^1.2.0" ou "1.2.3"

block_end         ::= ".end" ;

block             ::= block_head NL { block_stmt NL } block_end ;

block_stmt        ::= line_stmt | block ;       # blocs imbriqués autorisés

line_stmt         ::= line_head { WS1 line_arg } ;
line_head         ::= keyword ;                 # mots-clés réservés par contexte
line_arg          ::= atom ;

atom              ::= ident | string_lit | int_lit | float_lit | bool_lit ;

workspace_block   ::= "workspace" WS1 ident NL
                      { workspace_stmt NL }
                      ".end" ;

workspace_stmt    ::= "members" WS1 path_lit
                    | "default_profile" WS1 profile_name
                    ;

profile_name      ::= "dev" | "release" | ident ;
package_block     ::= "package" NL
                      { package_stmt NL }
                      ".end" ;

package_stmt      ::= "name" WS1 ident
                    | "version" WS1 semver_lit
                    | "edition" WS1 int_lit
                    | "license" WS1 string_lit
                    | "description" WS1 string_lit
                    | "authors" WS1 string_lit
                    | "repository" WS1 string_lit
                    | "homepage" WS1 string_lit
                    ;
                    target_block      ::= "target" WS1 target_kind WS1 ident NL
                      { target_stmt NL }
                      ".end" ;

target_kind       ::= "program" | "library" | "plugin" | "tool" ;

target_stmt       ::= "entry" WS1 path_lit
                    | "out" WS1 string_lit
                    | "emit" WS1 emit_kind
                    | "crate_type" WS1 crate_type
                    | "features" WS1 ident
                    | "defines" WS1 ident WS1 string_lit
                    | "link" WS1 link_kind WS1 string_lit
                    | "test" WS1 bool_lit
                    ;

emit_kind         ::= "native" | "c" | "bytecode" | "ir" ;
crate_type        ::= "static" | "shared" ;
link_kind         ::= "system" | "framework" | "static" | "shared" ;
deps_block        ::= "deps" NL
                      { dep_stmt NL }
                      ".end" ;

dep_stmt          ::= dep_path
                    | dep_git
                    | dep_ver
                    ;

dep_path          ::= ident WS1 "path" WS1 path_lit { WS1 dep_opt } ;
dep_git           ::= ident WS1 "git"  WS1 string_lit { WS1 dep_git_opt } { WS1 dep_opt } ;
dep_ver           ::= ident WS1 "ver"  WS1 semver_lit { WS1 dep_opt } ;

dep_git_opt       ::= ("rev" WS1 string_lit)
                    | ("tag" WS1 string_lit)
                    | ("branch" WS1 string_lit) ;

dep_opt           ::= ("optional" WS1 bool_lit)
                    | ("default_features" WS1 bool_lit)
                    | ("feature" WS1 ident) ;
                    profile_block     ::= "profile" WS1 profile_name NL
                      { profile_stmt NL }
                      ".end" ;

profile_stmt      ::= "opt" WS1 int_lit
                    | "debug" WS1 bool_lit
                    | "lto" WS1 bool_lit
                    | "strip" WS1 bool_lit
                    | "sanitize" WS1 sanitize_kind
                    | "panic" WS1 panic_kind
                    ;

sanitize_kind     ::= "none" | "address" | "undefined" | "thread" ;
panic_kind        ::= "abort" | "unwind" ;

toolchain_block   ::= "toolchain" NL
                      { toolchain_stmt NL }
                      ".end" ;

toolchain_stmt    ::= "backend" WS1 backend_kind
                    | "cc" WS1 string_lit
                    | "ar" WS1 string_lit
                    | "ld" WS1 string_lit
                    | "cflags" WS1 string_lit
                    | "ldflags" WS1 string_lit
                    | "sysroot" WS1 path_lit
                    ;

backend_kind      ::= "c" | "vm" ;