[build]
rustflags = ["-Dwarnings"]

[doc]
rustdocflags = ["-Dwarnings"]

[env]
RUST_BACKTRACE = "1"
CARGO_TERM_COLOR = "always"

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = ["-C","link-arg=-target","-C","link-arg=x86_64-apple-macos11"]
