// -----------------------------------------
// Generated by Vitte compiler (C++ backend)
// -----------------------------------------

#include <cstdint>
#include <cstdlib>
#include "vitte_runtime.hpp"
#include <cstddef>

enum class std__core__types__Unit {
    Unit
};

enum class std__core__types__Never {
};

enum class std__core__cmp__Ordering {
    Less,
    Equal,
    Greater
};

struct std__core__types__Bounds {
    void* min;
    void* max;
};

struct std__core__cmp__Eq {
    bool (*eq)(void*, void*);
};

struct std__core__cmp__Ord {
    std__core__cmp__Ordering (*cmp)(void*, void*);
};

struct std__core__option__Option {
    uint8_t __tag;
    void* value;
};

std__core__option__Option vitte__std__core__option__Option__Some(void* value);
std__core__option__Option vitte__std__core__option__Option__None();
bool vitte__std__core__cmp__is_eq(void* a, void* b, std__core__cmp__Eq impl);
bool vitte__std__core__cmp__is_ne(void* a, void* b, std__core__cmp__Eq impl);
bool vitte__std__core__cmp__is_lt(void* a, void* b, std__core__cmp__Ord impl);
bool vitte__std__core__cmp__is_le(void* a, void* b, std__core__cmp__Ord impl);
bool vitte__std__core__cmp__is_gt(void* a, void* b, std__core__cmp__Ord impl);
bool vitte__std__core__cmp__is_ge(void* a, void* b, std__core__cmp__Ord impl);
void* vitte__std__core__cmp__min(void* a, void* b, std__core__cmp__Ord impl);
void* vitte__std__core__cmp__max(void* a, void* b, std__core__cmp__Ord impl);
void* vitte__std__core__cmp__clamp(void* value, void* low, void* high, std__core__cmp__Ord impl);
std__core__option__Option vitte__std__core__option__some(void* value);
std__core__option__Option vitte__std__core__option__none();
bool vitte__std__core__option__is_some(std__core__option__Option opt);
bool vitte__std__core__option__is_none(std__core__option__Option opt);
void* vitte__std__core__option__unwrap(std__core__option__Option opt);
void* vitte__std__core__option__unwrap_or(std__core__option__Option opt, void* default_);
std__core__option__Option vitte__std__core__option__map(std__core__option__Option opt, void* (*f)(void*));
void* vitte__std__core__option__map_or(std__core__option__Option opt, void* default_, void* (*f)(void*));
std__core__option__Option vitte__std__core__option__and_then(std__core__option__Option opt, std__core__option__Option (*f)(void*));
std__core__option__Option vitte__std__core__option__or_else(std__core__option__Option opt, std__core__option__Option (*f)());
bool vitte__std__core__option__eq(std__core__option__Option a, std__core__option__Option b, std__core__cmp__Eq impl);
void vitte__std__core__panic__panic(VitteString msg);
void vitte__std__core__panic__abort();
void vitte__std__core__panic__assert(bool cond);
void vitte__std__core__panic__assert_msg(bool cond, VitteString msg);
void vitte__std__core__panic__unreachable();
void* vitte__std__core__panic__expect(std__core__option__Option opt, VitteString msg);
void* vitte__std__core__panic__unwrap(std__core__option__Option opt);
VitteSlice<int32_t> vitte__generate(int32_t seed, int32_t slots);
int32_t vitte__sum(VitteSlice<int32_t> values);
int32_t vitte__peak(VitteSlice<int32_t> values);
int32_t vitte__action(int32_t total, int32_t minv, int32_t p);
extern "C" void vitte__main();
int32_t main(int32_t argc, const char** argv);

const std__core__option__Option std__core__option__Option__None__value = vitte__std__core__option__Option__None();
std__core__option__Option vitte__std__core__option__Option__Some(void* value) {
    std__core__option__Option _v;
    _v.__tag = 0;
    _v.value = value;
    return _v;
}

std__core__option__Option vitte__std__core__option__Option__None() {
    std__core__option__Option _v;
    _v.__tag = 1;
    return _v;
}

bool vitte__std__core__cmp__is_eq(void* a, void* b, std__core__cmp__Eq impl) {
    bool _t0;
    bb_0_0:
    _t0 = impl.eq(a, b);
    return _t0;
}

bool vitte__std__core__cmp__is_ne(void* a, void* b, std__core__cmp__Eq impl) {
    bool _t0;
    int32_t _t1;
    bb_1_0:
    _t0 = impl.eq(a, b);
    _t1 = (_t0 == 0);
    return _t1;
}

bool vitte__std__core__cmp__is_lt(void* a, void* b, std__core__cmp__Ord impl) {
    std__core__cmp__Ordering _t0;
    bool _t1;
    bb_2_0:
    _t0 = impl.cmp(a, b);
    _t1 = (_t0 == std__core__cmp__Ordering::Less);
    return _t1;
}

bool vitte__std__core__cmp__is_le(void* a, void* b, std__core__cmp__Ord impl) {
    std__core__cmp__Ordering _t0;
    std__core__cmp__Ordering o;
    bool _t1;
    bool _t2;
    bool _t3;
    bb_3_0:
    _t0 = impl.cmp(a, b);
    o = _t0;
    _t1 = (o == std__core__cmp__Ordering::Less);
    _t2 = (o == std__core__cmp__Ordering::Equal);
    _t3 = (_t1 || _t2);
    return _t3;
}

bool vitte__std__core__cmp__is_gt(void* a, void* b, std__core__cmp__Ord impl) {
    std__core__cmp__Ordering _t0;
    bool _t1;
    bb_4_0:
    _t0 = impl.cmp(a, b);
    _t1 = (_t0 == std__core__cmp__Ordering::Greater);
    return _t1;
}

bool vitte__std__core__cmp__is_ge(void* a, void* b, std__core__cmp__Ord impl) {
    std__core__cmp__Ordering _t0;
    std__core__cmp__Ordering o;
    bool _t1;
    bool _t2;
    bool _t3;
    bb_5_0:
    _t0 = impl.cmp(a, b);
    o = _t0;
    _t1 = (o == std__core__cmp__Ordering::Greater);
    _t2 = (o == std__core__cmp__Ordering::Equal);
    _t3 = (_t1 || _t2);
    return _t3;
}

void* vitte__std__core__cmp__min(void* a, void* b, std__core__cmp__Ord impl) {
    std__core__cmp__Ordering _t0;
    bool _t1;
    bb_6_0:
    _t0 = impl.cmp(a, b);
    _t1 = (_t0 == std__core__cmp__Ordering::Greater);
    if (_t1) {
        goto bb_6_1;
    } else {
        goto bb_6_2;
    }
    bb_6_1:
    return b;
    bb_6_2:
    goto bb_6_3;
    bb_6_3:
    return a;
}

void* vitte__std__core__cmp__max(void* a, void* b, std__core__cmp__Ord impl) {
    std__core__cmp__Ordering _t0;
    bool _t1;
    bb_7_0:
    _t0 = impl.cmp(a, b);
    _t1 = (_t0 == std__core__cmp__Ordering::Less);
    if (_t1) {
        goto bb_7_1;
    } else {
        goto bb_7_2;
    }
    bb_7_1:
    return b;
    bb_7_2:
    goto bb_7_3;
    bb_7_3:
    return a;
}

void* vitte__std__core__cmp__clamp(void* value, void* low, void* high, std__core__cmp__Ord impl) {
    std__core__cmp__Ordering _t0;
    bool _t1;
    std__core__cmp__Ordering _t2;
    bool _t3;
    bb_8_0:
    _t0 = impl.cmp(value, low);
    _t1 = (_t0 == std__core__cmp__Ordering::Less);
    if (_t1) {
        goto bb_8_1;
    } else {
        goto bb_8_2;
    }
    bb_8_1:
    return low;
    bb_8_2:
    goto bb_8_3;
    bb_8_3:
    _t2 = impl.cmp(value, high);
    _t3 = (_t2 == std__core__cmp__Ordering::Greater);
    if (_t3) {
        goto bb_8_4;
    } else {
        goto bb_8_5;
    }
    bb_8_4:
    return high;
    bb_8_5:
    goto bb_8_6;
    bb_8_6:
    return value;
}

std__core__option__Option vitte__std__core__option__some(void* value) {
    std__core__option__Option _t0;
    bb_9_0:
    _t0 = vitte__std__core__option__Option__Some(value);
    return _t0;
}

std__core__option__Option vitte__std__core__option__none() {
    bb_10_0:
    return std__core__option__Option__None__value;
}

bool vitte__std__core__option__is_some(std__core__option__Option opt) {
    std__core__option__Option _t0;
    bool _t1;
    bb_11_0:
    _t0 = opt;
    goto bb_11_2;
    bb_11_1:
    return false;
    bb_11_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_11_3;
    } else {
        goto bb_11_4;
    }
    bb_11_3:
    return true;
    bb_11_4:
    goto bb_11_1;
}

bool vitte__std__core__option__is_none(std__core__option__Option opt) {
    std__core__option__Option _t0;
    bool _t1;
    bb_12_0:
    _t0 = opt;
    goto bb_12_2;
    bb_12_1:
    return false;
    bb_12_2:
    _t1 = (_t0.__tag == 1);
    if (_t1) {
        goto bb_12_3;
    } else {
        goto bb_12_4;
    }
    bb_12_3:
    return true;
    bb_12_4:
    goto bb_12_1;
}

void* vitte__std__core__option__unwrap(std__core__option__Option opt) {
    std__core__option__Option _t0;
    bool _t1;
    bb_13_0:
    _t0 = opt;
    goto bb_13_2;
    bb_13_1:
    vitte_builtin_trap(VitteString{"called unwrap on Option.None", 28});
    bb_13_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_13_3;
    } else {
        goto bb_13_4;
    }
    bb_13_3:
    return opt.value;
    bb_13_4:
    goto bb_13_1;
}

void* vitte__std__core__option__unwrap_or(std__core__option__Option opt, void* default_) {
    std__core__option__Option _t0;
    bool _t1;
    bb_14_0:
    _t0 = opt;
    goto bb_14_2;
    bb_14_1:
    return default_;
    bb_14_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_14_3;
    } else {
        goto bb_14_4;
    }
    bb_14_3:
    return opt.value;
    bb_14_4:
    goto bb_14_1;
}

std__core__option__Option vitte__std__core__option__map(std__core__option__Option opt, void* (*f)(void*)) {
    std__core__option__Option _t0;
    bool _t1;
    void* _t2;
    std__core__option__Option _t3;
    bb_15_0:
    _t0 = opt;
    goto bb_15_2;
    bb_15_1:
    return std__core__option__Option__None__value;
    bb_15_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_15_3;
    } else {
        goto bb_15_4;
    }
    bb_15_3:
    _t2 = f(opt.value);
    _t3 = vitte__std__core__option__Option__Some(_t2);
    return _t3;
    bb_15_4:
    goto bb_15_1;
}

void* vitte__std__core__option__map_or(std__core__option__Option opt, void* default_, void* (*f)(void*)) {
    std__core__option__Option _t0;
    bool _t1;
    void* _t2;
    bb_16_0:
    _t0 = opt;
    goto bb_16_2;
    bb_16_1:
    return default_;
    bb_16_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_16_3;
    } else {
        goto bb_16_4;
    }
    bb_16_3:
    _t2 = f(opt.value);
    return _t2;
    bb_16_4:
    goto bb_16_1;
}

std__core__option__Option vitte__std__core__option__and_then(std__core__option__Option opt, std__core__option__Option (*f)(void*)) {
    std__core__option__Option _t0;
    bool _t1;
    std__core__option__Option _t2;
    bb_17_0:
    _t0 = opt;
    goto bb_17_2;
    bb_17_1:
    return std__core__option__Option__None__value;
    bb_17_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_17_3;
    } else {
        goto bb_17_4;
    }
    bb_17_3:
    _t2 = f(opt.value);
    return _t2;
    bb_17_4:
    goto bb_17_1;
}

std__core__option__Option vitte__std__core__option__or_else(std__core__option__Option opt, std__core__option__Option (*f)()) {
    std__core__option__Option _t0;
    bool _t1;
    std__core__option__Option _t2;
    bb_18_0:
    _t0 = opt;
    goto bb_18_2;
    bb_18_1:
    _t2 = f();
    return _t2;
    bb_18_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_18_3;
    } else {
        goto bb_18_4;
    }
    bb_18_3:
    return opt;
    bb_18_4:
    goto bb_18_1;
}

bool vitte__std__core__option__eq(std__core__option__Option a, std__core__option__Option b, std__core__cmp__Eq impl) {
    std__core__option__Option _t0;
    bool _t1;
    std__core__option__Option _t2;
    bool _t3;
    bool _t4;
    std__core__option__Option _t5;
    bool _t6;
    bb_19_0:
    _t0 = a;
    goto bb_19_2;
    bb_19_1:
    _t5 = b;
    goto bb_19_10;
    bb_19_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_19_3;
    } else {
        goto bb_19_4;
    }
    bb_19_3:
    _t2 = b;
    goto bb_19_6;
    bb_19_4:
    goto bb_19_1;
    bb_19_5:
    return false;
    bb_19_6:
    _t3 = (_t2.__tag == 0);
    if (_t3) {
        goto bb_19_7;
    } else {
        goto bb_19_8;
    }
    bb_19_7:
    _t4 = impl.eq(a.value, b.value);
    return _t4;
    bb_19_8:
    goto bb_19_5;
    bb_19_9:
    return false;
    bb_19_10:
    _t6 = (_t5.__tag == 1);
    if (_t6) {
        goto bb_19_11;
    } else {
        goto bb_19_12;
    }
    bb_19_11:
    return true;
    bb_19_12:
    goto bb_19_9;
}

void vitte__std__core__panic__panic(VitteString msg) {
    bb_20_0:
    vitte_builtin_trap(msg);
}

void vitte__std__core__panic__abort() {
    bb_21_0:
    vitte_builtin_trap(VitteString{"abort", 5});
}

void vitte__std__core__panic__assert(bool cond) {
    int32_t _t0;
    bb_22_0:
    _t0 = (cond == 0);
    if (_t0) {
        goto bb_22_1;
    } else {
        goto bb_22_2;
    }
    bb_22_1:
    vitte__std__core__panic__panic(VitteString{"assertion failed", 16});
    goto bb_22_3;
    bb_22_2:
    goto bb_22_3;
    bb_22_3:
}

void vitte__std__core__panic__assert_msg(bool cond, VitteString msg) {
    int32_t _t0;
    bb_23_0:
    _t0 = (cond == 0);
    if (_t0) {
        goto bb_23_1;
    } else {
        goto bb_23_2;
    }
    bb_23_1:
    vitte__std__core__panic__panic(msg);
    goto bb_23_3;
    bb_23_2:
    goto bb_23_3;
    bb_23_3:
}

void vitte__std__core__panic__unreachable() {
    bb_24_0:
    vitte_builtin_trap(VitteString{"unreachable", 11});
}

void* vitte__std__core__panic__expect(std__core__option__Option opt, VitteString msg) {
    std__core__option__Option _t0;
    bool _t1;
    bb_25_0:
    _t0 = opt;
    goto bb_25_2;
    bb_25_1:
    vitte__std__core__panic__panic(msg);
    bb_25_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_25_3;
    } else {
        goto bb_25_4;
    }
    bb_25_3:
    return opt.value;
    bb_25_4:
    goto bb_25_1;
}

void* vitte__std__core__panic__unwrap(std__core__option__Option opt) {
    std__core__option__Option _t0;
    bool _t1;
    bb_26_0:
    _t0 = opt;
    goto bb_26_2;
    bb_26_1:
    vitte__std__core__panic__panic(VitteString{"called unwrap on None", 21});
    bb_26_2:
    _t1 = (_t0.__tag == 0);
    if (_t1) {
        goto bb_26_3;
    } else {
        goto bb_26_4;
    }
    bb_26_3:
    return opt.value;
    bb_26_4:
    goto bb_26_1;
}

VitteSlice<int32_t> vitte__generate(int32_t seed, int32_t slots) {
    VitteSlice<int32_t> _t0;
    VitteSlice<int32_t> out;
    int32_t i;
    bool _t1;
    int32_t _t2;
    int32_t _t3;
    int32_t _t4;
    int32_t _t5;
    int32_t _t6;
    int32_t v;
    VitteSlice<int32_t> _t7;
    int32_t _t8;
    bb_27_0:
    _t0 = vitte__vitte_empty_slice_i32();
    out = _t0;
    i = 0;
    goto bb_27_1;
    bb_27_1:
    _t1 = (i >= slots);
    if (_t1) {
        goto bb_27_3;
    } else {
        goto bb_27_4;
    }
    bb_27_2:
    return out;
    bb_27_3:
    goto bb_27_2;
    bb_27_4:
    goto bb_27_5;
    bb_27_5:
    _t2 = (seed * 19);
    _t3 = (i * 7);
    _t4 = (_t2 + _t3);
    _t5 = (_t4 + 127);
    _t6 = (_t5 + 160);
    v = _t6;
    _t7 = vitte__vitte_slice_push_i32(out, v);
    out = _t7;
    _t8 = (i + 1);
    i = _t8;
    goto bb_27_1;
}

int32_t vitte__sum(VitteSlice<int32_t> values) {
    size_t i;
    int32_t acc;
    bool _t0;
    int32_t _t1;
    int32_t _t2;
    bb_28_0:
    i = 0;
    acc = 0;
    goto bb_28_1;
    bb_28_1:
    _t0 = (i >= values.len);
    if (_t0) {
        goto bb_28_3;
    } else {
        goto bb_28_4;
    }
    bb_28_2:
    return acc;
    bb_28_3:
    goto bb_28_2;
    bb_28_4:
    goto bb_28_5;
    bb_28_5:
    _t1 = (acc + values.data[i]);
    acc = _t1;
    _t2 = (i + 1);
    i = _t2;
    goto bb_28_1;
}

int32_t vitte__peak(VitteSlice<int32_t> values) {
    bool _t0;
    size_t i;
    int32_t m;
    bool _t1;
    bool _t2;
    int32_t _t3;
    bb_29_0:
    _t0 = (values.len == 0);
    if (_t0) {
        goto bb_29_1;
    } else {
        goto bb_29_2;
    }
    bb_29_1:
    return 0;
    bb_29_2:
    goto bb_29_3;
    bb_29_3:
    i = 1;
    m = values.data[0];
    goto bb_29_4;
    bb_29_4:
    _t1 = (i >= values.len);
    if (_t1) {
        goto bb_29_6;
    } else {
        goto bb_29_7;
    }
    bb_29_5:
    return m;
    bb_29_6:
    goto bb_29_5;
    bb_29_7:
    goto bb_29_8;
    bb_29_8:
    _t2 = (values.data[i] > m);
    if (_t2) {
        goto bb_29_9;
    } else {
        goto bb_29_10;
    }
    bb_29_9:
    m = values.data[i];
    goto bb_29_11;
    bb_29_10:
    goto bb_29_11;
    bb_29_11:
    _t3 = (i + 1);
    i = _t3;
    goto bb_29_4;
}

int32_t vitte__action(int32_t total, int32_t minv, int32_t p) {
    int32_t _t0;
    int32_t _t1;
    int32_t gate;
    bool _t2;
    int32_t _t3;
    bb_30_0:
    _t0 = (total + p);
    _t1 = (_t0 + 100);
    gate = _t1;
    _t2 = (gate < minv);
    if (_t2) {
        goto bb_30_1;
    } else {
        goto bb_30_2;
    }
    bb_30_1:
    _t3 = (minv - gate);
    return _t3;
    bb_30_2:
    goto bb_30_3;
    bb_30_3:
    return 0;
}

extern "C" void vitte__main() {
    VitteSlice<int32_t> _t0;
    VitteSlice<int32_t> values;
    int32_t _t1;
    int32_t total;
    int32_t _t2;
    int32_t p;
    int32_t _t3;
    int32_t a;
    int32_t _t4;
    int32_t _t5;
    int32_t score;
    bool _t6;
    VitteString _t7;
    VitteString _t8;
    VitteString label;
    bb_31_0:
    _t0 = vitte__generate(127, 102);
    values = _t0;
    _t1 = vitte__sum(values);
    total = _t1;
    _t2 = vitte__peak(values);
    p = _t2;
    _t3 = vitte__action(total, 35, p);
    a = _t3;
    _t4 = (total + p);
    _t5 = (_t4 + a);
    score = _t5;
    _t6 = (score >= 0);
    vitte__std__core__panic__assert(_t6);
    _t7 = vitte__vitte_i32_to_string(score);
    _t8 = vitte__vitte_string_concat(VitteString{"core-harbor-score:", 18}, _t7);
    label = _t8;
    auto _ = label.len;
    return;
}

int32_t main(int32_t argc, const char** argv) {
    vitte_set_args(argc, argv);
    vitte__main();
    return 0;
}

