#include "emit.hpp"

#include "../context/cpp_context.hpp"

#include <fstream>
#include <iostream>

namespace vitte::backend::emit {

/* -------------------------------------------------
 * Emit translation unit to file
 * ------------------------------------------------- */
bool emit_file(
    const std::string& path,
    const ast::cpp::CppTranslationUnit& tu,
    context::CppContext& ctx
) {
    std::ofstream out(path);
    if (!out.is_open()) {
        std::cerr << "[emit] failed to open output file: " << path << "\n";
        return false;
    }

    /* ---------------------------------------------
     * File header
     * --------------------------------------------- */
    out << "// -----------------------------------------\n";
    out << "// Generated by Vitte compiler (C++ backend)\n";
    out << "// -----------------------------------------\n\n";

    /* ---------------------------------------------
     * Emit translation unit
     * --------------------------------------------- */
    emit_translation_unit(out, tu, ctx);

    out.flush();
    return true;
}

} // namespace vitte::backend::emit
