services:
  vitte-beta:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vitte-beta
    working_dir: /workspace/vitte
    volumes:
      - ../../:/workspace/vitte
    tty: true
    stdin_open: true
