.TH WTINIT 1 "630 MTG"
.SH NAME
wtinit - initialize 630 MTG terminal for layers environment
.SH SYNOPSIS
\fBwtinit\fR
.SH DESCRIPTION
.I Wtinit
is used by the UNIX layers(1) command to initialize the 630
MTG terminal
for the layers environment.
This is the 630 MTG terminal specific version of the UNIX windowing
utilities \fIwtinit\fR command.
Layers(1) will use $DMD/bin/wtinit if the $DMD variable is set.
.SH DIAGNOSTICS
\f2Wtinit\f1 is a shell program which uses the \f2dmdversion\f1(1) command to
determine if LAN encoding is set.
If \fIdmdversion\fR is not found a message is displayed.
.SH EXIT STATUS
Returns 0 upon successful completion, 1 otherwise.
.SH SEE ALSO
layers(1) in the
\f2UNIX System V Release 3 User's Reference Manual\f1.
.br
wtinit(1) in the
\f2UNIX System V Release 3 System Administrator's Reference Manual\f1.
