(* Vitte field declarations grammar *)

field_declaration
    = field_attributes?,
      field_visibility?,
      field_mutability?,
      identifier,
      colon,
      type,
      field_default?,
      semicolon?
    ;

field_attributes
    = attribute, { attribute }
    ;

field_visibility
    = "public"
    | "package"
    | "private"
    ;

field_mutability
    = "mut"
    ;

field_default
    = "=",
      expression
    ;

field_declaration_list
    = field_declaration,
      { field_separator, field_declaration },
      field_separator?
    ;

field_separator
    = comma
    | semicolon
    ;

named_field_block
    = left_brace,
      field_declaration_list?,
      right_brace
    ;

tuple_field_declaration
    = field_attributes?,
      field_visibility?,
      type,
      field_default?
    ;

tuple_field_declaration_list
    = tuple_field_declaration,
      { comma, tuple_field_declaration },
      comma?
    ;

tuple_field_block
    = left_parenthesis,
      tuple_field_declaration_list?,
      right_parenthesis
    ;

field_initializer
    = identifier,
      colon,
      expression
    | identifier
    ;

field_initializer_list
    = field_initializer,
      { comma, field_initializer },
      comma?
    ;

field_initializer_block
    = left_brace,
      field_initializer_list?,
      right_brace
    ;

field_pattern
    = identifier,
      colon,
      pattern
    | identifier
    | ".."
    ;

field_pattern_list
    = field_pattern,
      { comma, field_pattern },
      comma?
    ;

field_pattern_block
    = left_brace,
      field_pattern_list?,
      right_brace
    ;

field_access
    = expression,
      dot,
      identifier
    ;

tuple_field_access
    = expression,
      dot,
      decimal_integer_literal
    ;

left_brace
    = "{"
    ;

right_brace
    = "}"
    ;

left_parenthesis
    = "("
    ;

right_parenthesis
    = ")"
    ;

colon
    = ":"
    ;

comma
    = ","
    ;

semicolon
    = ";"
    ;

dot
    = "."
    ;
