(* Vitte reserved keywords *)

keyword
    = declaration_keyword
    | module_keyword
    | visibility_keyword
    | binding_keyword
    | mutability_keyword
    | control_flow_keyword
    | pattern_keyword
    | type_keyword
    | boolean_keyword
    | literal_keyword
    | async_keyword
    | safety_keyword
    | compiler_keyword
    | operator_keyword
    | path_keyword
    ;

declaration_keyword
    = "space"
    | "use"
    | "export"
    | "as"
    | "proc"
    | "form"
    | "pick"
    | "trait"
    | "impl"
    | "type"
    | "const"
    | "static"
    | "macro"
    | "extern"
    ;

module_keyword
    = "package"
    | "module"
    ;

visibility_keyword
    = "public"
    | "private"
    | "internal"
    ;

binding_keyword
    = "let"
    | "set"
    | "give"
    | "return"
    ;

mutability_keyword
    = "mut"
    | "ref"
    | "move"
    | "copy"
    ;

control_flow_keyword
    = "if"
    | "else"
    | "pick"
    | "while"
    | "loop"
    | "for"
    | "in"
    | "break"
    | "continue"
    | "defer"
    ;

pattern_keyword
    = "where"
    | "match"
    ;

type_keyword
    = "dynamic"
    | "sizeof"
    | "alignof"
    | "typeof"
    ;

boolean_keyword
    = "true"
    | "false"
    ;

literal_keyword
    = "null"
    ;

async_keyword
    = "async"
    | "await"
    ;

safety_keyword
    = "unsafe"
    | "try"
    ;

compiler_keyword
    = "compiler"
    ;

operator_keyword
    = "and"
    | "or"
    | "not"
    | "is"
    ;

path_keyword
    = "self"
    | "super"
    | "root"
    ;

reserved_future_keyword
    = "abstract"
    | "become"
    | "box"
    | "concept"
    | "do"
    | "enum"
    | "final"
    | "friend"
    | "goto"
    | "interface"
    | "namespace"
    | "override"
    | "overrideable"
    | "package_private"
    | "partial"
    | "protected"
    | "sealed"
    | "synchronized"
    | "this"
    | "throw"
    | "throws"
    | "virtual"
    | "volatile"
    | "yield"
    ;
