(* Vitte operators grammar *)

operator
    = assignment_operator
    | arithmetic_operator
    | comparison_operator
    | logical_operator
    | bitwise_operator
    | shift_operator
    | range_operator
    | unary_operator
    | cast_operator
    | member_operator
    | call_operator
    | indexing_operator
    | path_operator
    | punctuation_operator
    ;

assignment_operator
    = "="
    | "+="
    | "-="
    | "*="
    | "/="
    | "%="
    | "&="
    | "|="
    | "^="
    | "<<="
    | ">>="
    ;

arithmetic_operator
    = "+"
    | "-"
    | "*"
    | "/"
    | "%"
    ;

comparison_operator
    = "=="
    | "!="
    | "<"
    | "<="
    | ">"
    | ">="
    | "is"
    | "is", "not"
    | "in"
    | "not", "in"
    ;

logical_operator
    = "!"
    | "&&"
    | "||"
    | "and"
    | "or"
    | "not"
    ;

bitwise_operator
    = "&"
    | "|"
    | "^"
    | "~"
    ;

shift_operator
    = "<<"
    | ">>"
    ;

range_operator
    = ".."
    | "..="
    ;

unary_operator
    = "+"
    | "-"
    | "!"
    | "~"
    | "*"
    | "&"
    | "ref"
    | "ref", "mut"
    | "await"
    | "try"
    ;

cast_operator
    = "as"
    ;

member_operator
    = "."
    ;

call_operator
    = "(",
      ")"
    ;

indexing_operator
    = "[",
      "]"
    ;

path_operator
    = "::"
    | "/"
    ;

punctuation_operator
    = "->"
    | "=>"
    | "?"
    | "@"
    | ":"
    | ","
    | ";"
    ;
