.TH APX 8
.CT 1 sa_nonmortals secur
.SH NAME
apx \- mark an open stream device trusted
.SH SYNOPSIS
.B /etc/apx
[
.I arg
]
.SH DESCRIPTION
By default, a freshly opened stream device has the
.B APX
bit cleared: it will reject all pex requests.
If invoked without an argument,
.I apx
will set the APX bit on its standard input
(by calling the
.B FIOAPX
control).
If invoked without an argument the 
.B APX
bit is cleared.
.I Apx
needs licence
.B T_EXTERN
to run.
It is usually automatically invoked at login time,
provided that the source identifier of the standard input
of the login session is worthy.
.SH FILES
.F /etc/privs
.SH SEE ALSO
.IR pex (4)
