# Geany snippets for Vitte.
# Install by appending this file into ~/.config/geany/snippets.conf

[vitte]
entry_main=entry main at core/app {\n\t%cursor%\n\tgive 0\n}
proc=proc %cursor%() {\n\t%cursor%\n}
form=form %cursor% {\n\t%cursor%\n}
trait=trait %cursor% {\n\t%cursor%\n}

[Vitte]
entry_main=entry main at core/app {\n\t%cursor%\n\tgive 0\n}
proc=proc %cursor%() {\n\t%cursor%\n}
form=form %cursor% {\n\t%cursor%\n}
trait=trait %cursor% {\n\t%cursor%\n}
