#!/bin/sh
cd /usr/asd
PATH=/bin:/usr/bin
export PATH
TMP=/usr/asd/tmp
trap 'rm -f $TMP.1 $TMP.2; exit' 0 1 2 13 15
>$TMP.1
# TMP1 is cumulative list of all inspkg actions
for i in `ls -r [0-9]* `
do
	echo $i
	inspkg -nv $i 2>&1 | grep -v '^[0-9]*:$' | sort >$TMP.2
	if comm -12 $TMP.1 $TMP.2 | cmp /dev/stdin $TMP.2 >/dev/null
	then echo rm $i; rm $i
	else sort -m $TMP.1 $TMP.2 -o $TMP.1
	fi
done
