.TH LABMOUNT 2
.SH NAME
labmount \- return file system ceiling label
.SH SYNOPSIS
.B int labmount(fd, lp)
.br
.B struct label *lp;
.SH DESCRIPTION
If the file with descriptor
.I fd
resides in a file system,
.I labmount
copies the ceiling label of that file system into
the place pointed to by
.I lp.
If the file does not reside in a file system, the
ceiling is reported to be
.BR L_YES ;
see
.IR getflab (2).
.SH SEE ALSO
.IR fmount (2)
.SH DIAGNOSTICS
.L
EBADF, EFAULT, EIO, ELOOP, ENOENT, ENOTDIR
