.TH BLMOUNT 8
.CT 1 sa_nonmortals
.SH NAME
blmount \- mark directories blind
.SH SYNOPSIS
.B /etc/blmount
[
.B -u
]
.I directory
.SH DESCRIPTION
.I Blmount
without options
mounts the named directory on itself as a blind file system
.IR bl (4) .
With option
.BR -u ,
the treatment is reversed.
The 
.I directory
must be on a traditional (disk) file system.
.SH SEE ALSO
.IR bl (4)
