.TH MKUNIQUE 1 
.CT 1 shell
.SH NAME
mkunique \- create files with unique names
.SH SYNOPSIS
.B mkunique
[
.I template ...
]
.SH DESCRIPTION
.I Mkunique
uses the library function 
.IR mkunique (3)
to create
files with unique names,
one per specified template.
If no template is supplied,
.I mkunique 
creates a single file with template
.LR qXXXXXX .
The resulting file names are echoed on the standard output,
one per line.
.LP
This command may be used to create names for scratch files in 
publically shareable multilevel secure `blind' directories,
without violating security policy.
.SH SEE ALSO
.IR mkunique (3),
.IR mktemp (3),
.IR bl (4)
