// -----------------------------------------
// Generated by Vitte compiler (C++ backend)
// -----------------------------------------

#include <cstdint>
#include <cstdlib>
#include "vitte_runtime.hpp"
#include <cstddef>

enum class std__core__types__Unit {
    Unit
};

enum class std__core__types__Never {
};

enum class std__arduino__gpio__PinMode {
    Input,
    Output,
    InputPullup
};

enum class std__arduino__gpio__PinState {
    Low,
    High
};

struct std__core__types__Bounds {
    void* min;
    void* max;
};

extern "C" void std__arduino__gpio__arduino_gpio_pin_mode(uint8_t pin, std__arduino__gpio__PinMode mode);
extern "C" void std__arduino__gpio__arduino_gpio_digital_write(uint8_t pin, std__arduino__gpio__PinState state);
extern "C" std__arduino__gpio__PinState std__arduino__gpio__arduino_gpio_digital_read(uint8_t pin);
extern "C" void std__arduino__gpio__arduino_gpio_analog_write(uint8_t pin, uint16_t value);
extern "C" uint16_t std__arduino__gpio__arduino_gpio_analog_read(uint8_t pin);
void vitte__std__arduino__gpio__pin_mode(uint8_t pin, std__arduino__gpio__PinMode mode);
void vitte__std__arduino__gpio__digital_write(uint8_t pin, std__arduino__gpio__PinState state);
std__arduino__gpio__PinState vitte__std__arduino__gpio__digital_read(uint8_t pin);
void vitte__std__arduino__gpio__analog_write(uint8_t pin, uint16_t value);
uint16_t vitte__std__arduino__gpio__analog_read(uint8_t pin);
extern "C" void std__arduino__timer__arduino_delay_ms(uint32_t ms);
extern "C" void std__arduino__timer__arduino_delay_us(uint32_t us);
extern "C" uint32_t std__arduino__timer__arduino_millis();
extern "C" uint32_t std__arduino__timer__arduino_micros();
void vitte__std__arduino__timer__delay_ms(uint32_t ms);
void vitte__std__arduino__timer__delay_us(uint32_t us);
uint32_t vitte__std__arduino__timer__millis();
uint32_t vitte__std__arduino__timer__micros();
extern "C" void vitte__main();
void setup();
void loop();

extern "C" void std__arduino__gpio__arduino_gpio_pin_mode(uint8_t pin, std__arduino__gpio__PinMode mode);

extern "C" void std__arduino__gpio__arduino_gpio_digital_write(uint8_t pin, std__arduino__gpio__PinState state);

extern "C" std__arduino__gpio__PinState std__arduino__gpio__arduino_gpio_digital_read(uint8_t pin);

extern "C" void std__arduino__gpio__arduino_gpio_analog_write(uint8_t pin, uint16_t value);

extern "C" uint16_t std__arduino__gpio__arduino_gpio_analog_read(uint8_t pin);

void vitte__std__arduino__gpio__pin_mode(uint8_t pin, std__arduino__gpio__PinMode mode) {
    bb_5_0:
    std__arduino__gpio__arduino_gpio_pin_mode(pin, mode);
}

void vitte__std__arduino__gpio__digital_write(uint8_t pin, std__arduino__gpio__PinState state) {
    bb_6_0:
    std__arduino__gpio__arduino_gpio_digital_write(pin, state);
}

std__arduino__gpio__PinState vitte__std__arduino__gpio__digital_read(uint8_t pin) {
    std__arduino__gpio__PinState _t0;
    bb_7_0:
    _t0 = std__arduino__gpio__arduino_gpio_digital_read(pin);
    return _t0;
}

void vitte__std__arduino__gpio__analog_write(uint8_t pin, uint16_t value) {
    bb_8_0:
    std__arduino__gpio__arduino_gpio_analog_write(pin, value);
}

uint16_t vitte__std__arduino__gpio__analog_read(uint8_t pin) {
    uint16_t _t0;
    bb_9_0:
    _t0 = std__arduino__gpio__arduino_gpio_analog_read(pin);
    return _t0;
}

extern "C" void std__arduino__timer__arduino_delay_ms(uint32_t ms);

extern "C" void std__arduino__timer__arduino_delay_us(uint32_t us);

extern "C" uint32_t std__arduino__timer__arduino_millis();

extern "C" uint32_t std__arduino__timer__arduino_micros();

void vitte__std__arduino__timer__delay_ms(uint32_t ms) {
    bb_14_0:
    std__arduino__timer__arduino_delay_ms(ms);
}

void vitte__std__arduino__timer__delay_us(uint32_t us) {
    bb_15_0:
    std__arduino__timer__arduino_delay_us(us);
}

uint32_t vitte__std__arduino__timer__millis() {
    uint32_t _t0;
    bb_16_0:
    _t0 = std__arduino__timer__arduino_millis();
    return _t0;
}

uint32_t vitte__std__arduino__timer__micros() {
    uint32_t _t0;
    bb_17_0:
    _t0 = std__arduino__timer__arduino_micros();
    return _t0;
}

extern "C" void vitte__main() {
    bb_18_0:
    vitte__std__arduino__gpio__pin_mode(13, std__arduino__gpio__PinMode::Output);
    vitte__std__arduino__timer__delay_ms(1);
    return;
}

void setup() {
    vitte__main();
}

void loop() {
}

