[package]
name        = "vitte-bench"
description = "Benchmarks suite for Vitte (lexer, parser, VM, IR passes)."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-bench"

keywords   = ["compiler", "benchmark", "performance", "vitte"]
categories = ["compilers", "development-tools", "benchmark"]

exclude = [".github/*", "scripts/*"]

[lib]
name = "vitte_bench"
path = "src/lib.rs"
bench = false

[features]
default = ["std"]
std     = []

# option benchmarks micro VM
vm-micro = []

# option benchmarks end-to-end
e2e = []

# full = tout activé
full = ["std", "vm-micro", "e2e"]

[dependencies]
criterion = { version = "0.5", default-features = false }
rand      = "0.8"
anyhow    = "1"
tempfile  = "3"

vitte-cli      = { path = "../vitte-cli" }
vitte-compiler = { path = "../vitte-compiler" }
vitte-core     = { path = "../vitte-core" }
vitte-lexer    = { path = "../vitte-lexer" }
vitte-parser   = { path = "../vitte-parser" }
vitte-vm       = { path = "../vitte-vm" }

serde      = { workspace = true, optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
serde_json        = "1.0"
pretty_assertions = { workspace = true }

[[bench]]
name    = "lexer"
harness = false

[[bench]]
name    = "parser"
harness = false

[[bench]]
name    = "vm_hotpath"
harness = false

[[bench]]
name    = "vm_micro"
harness = false

[[bench]]
name    = "e2e_pipeline"
harness = false

[[bench]]
name    = "end_to_end"
harness = false

[[bench]]
name    = "ir_passes"
harness = false

[package.metadata.docs.rs]
all-features = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                      = "warn"
pedantic                 = "warn"
nursery                  = "warn"
module_name_repetitions  = "allow"
doc_markdown             = "allow"
too_many_lines           = "allow"
