import { promises as fs } from 'node:fs';
import path from 'node:path';

const EXCLUDED_DIRS = new Set([
  '.git',
  'node_modules',
  'out',
  'dist',
  'build',
  'target',
  '.next',
]);

function isSourceFile(filePath) {
  return /\.(?:vit|vitl|vitte)$/i.test(filePath);
}

function shouldKeepModuleName(name) {
  const excludedSegments = new Set(['private', 'stdlib_checked', 'kernel_name']);
  return !name.split(/[/.]/).some((segment) => {
    const normalized = segment.toLowerCase();
    return excludedSegments.has(normalized)
      || normalized === 'test'
      || normalized === 'tests'
      || normalized.startsWith('test_');
  });
}

async function walk(dir, out) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (EXCLUDED_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full, out);
    } else if (entry.isFile() && isSourceFile(full)) {
      out.push(full);
    }
  }
}

async function isDirectory(candidate) {
  try {
    return (await fs.stat(candidate)).isDirectory();
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      return false;
    }
    throw error;
  }
}

export async function readVitteImportNames(repoRoot) {
  const configuredRoot = process.env.VITTE_SOURCE_ROOT;
  const candidates = configuredRoot
    ? [path.resolve(repoRoot, configuredRoot)]
    : [path.join(repoRoot, 'src', 'vitte'), path.join(repoRoot, 'modules')];
  const sourceRoots = [];

  for (const candidate of candidates) {
    if (await isDirectory(candidate)) sourceRoots.push(candidate);
  }

  if (sourceRoots.length === 0) return undefined;

  const files = [];
  for (const sourceRoot of sourceRoots) await walk(sourceRoot, files);

  const moduleNames = new Set();
  for (const file of files) {
    const text = await fs.readFile(file, 'utf8');
    const match = /^\s*space\s+([^\s;]+)/m.exec(text);
    if (!match) continue;
    const moduleName = match[1].trim();
    if (shouldKeepModuleName(moduleName)) moduleNames.add(moduleName);
  }

  return Array.from(moduleNames).sort((a, b) => a.localeCompare(b));
}

export function renderVitteImports(moduleNames) {
  return [
    '// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.',
    '// Generated by: scripts/generate-vitte-imports.mjs',
    '',
    'export const VITTE_PACKAGE_IMPORTS: readonly string[] = [',
    ...moduleNames.map((name) => `  ${JSON.stringify(name)},`),
    '];',
    '',
  ].join('\n');
}
