.TH LABCONST 3
.SH NAME
labelyes, labelno, labeltop, labelbot \- label constants
.SH SYNOPSIS
.B extern struct label labelyes;
.PP
.B extern struct label labelno;
.PP
.B extern struct label labeltop;
.PP
.B extern struct label labelbot;
.SH DESCRIPTION
These objects are initialized as follows, where the
coded values are as in
.IR labtoa (3).
.TF labeltop
.TP
.B labelyes
The universally permissive label,
.LR Y .
.TP
.B labelno
The universally denying label,
.LR N .
.TP
.B labeltop
The top lattice value,
.LR ffff... .
.TP
.B labelbot
The bottom lattice value,
.LR 0000... .
