[package]
name        = "vitte-green"
description = "Collecteur de graphe et moteur d’invalidation verte pour Vitte."

version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }

readme        = "README.md"
documentation = "https://docs.rs/vitte-green"

keywords   = ["incremental", "dependency", "vitte"]
categories = ["development-tools"]

exclude = [".github/*", "examples/*", "tests/*"]

[lib]
name = "vitte_green"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std = []

[dependencies]

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all                     = "warn"
pedantic                = "warn"
nursery                 = "warn"
module_name_repetitions = "allow"
doc_markdown            = "allow"
too_many_lines          = "allow"
