#!/usr/bin/env bash
set -euo pipefail

detect_geany_home() {
  if [[ -n "${GEANY_HOME:-}" ]]; then
    printf "%s\n" "$GEANY_HOME"
    return
  fi
  case "$(uname -s 2>/dev/null || echo unknown)" in
    Darwin)
      printf "%s\n" "$HOME/Library/Application Support/geany"
      ;;
    MINGW*|MSYS*|CYGWIN*)
      if [[ -n "${APPDATA:-}" ]]; then
        printf "%s\n" "$APPDATA/geany"
      else
        printf "%s\n" "$HOME/AppData/Roaming/geany"
      fi
      ;;
    *)
      printf "%s\n" "${XDG_CONFIG_HOME:-$HOME/.config}/geany"
      ;;
  esac
}

GEANY_HOME="$(detect_geany_home)"
FILEDEFS="$GEANY_HOME/filedefs/filetypes.vitte.conf"
EXT_FILE="$GEANY_HOME/filetype_extensions.conf"
SNIPPETS_FILE="$GEANY_HOME/snippets.conf"

err=0

if [[ ! -f "$FILEDEFS" ]]; then
  echo "[geany-check][error] missing $FILEDEFS" >&2
  err=1
else
  grep -q "AUTO-GENERATED by tools/generate_editor_highlights.py" "$FILEDEFS" || {
    echo "[geany-check][error] missing generated header in $FILEDEFS" >&2
    err=1
  }
fi

if [[ ! -f "$EXT_FILE" ]]; then
  echo "[geany-check][error] missing $EXT_FILE" >&2
  err=1
else
  grep -Eq '^(Vitte|vitte)=.*\*\.vit' "$EXT_FILE" || {
    echo "[geany-check][error] missing *.vit association in $EXT_FILE" >&2
    err=1
  }
fi

if [[ ! -f "$SNIPPETS_FILE" ]]; then
  echo "[geany-check][error] missing $SNIPPETS_FILE" >&2
  err=1
else
  grep -Eq '^\[(vitte|Vitte)\]$' "$SNIPPETS_FILE" || {
    echo "[geany-check][error] missing [vitte]/[Vitte] snippets section in $SNIPPETS_FILE" >&2
    err=1
  }
fi

if [[ "$err" -ne 0 ]]; then
  exit 2
fi

echo "[geany-check] OK GEANY_HOME=$GEANY_HOME"
