#!/usr/bin/env bash
set -euo pipefail

detect_geany_homes() {
  if [[ -n "${GEANY_HOME:-}" ]]; then
    printf "%s\n" "$GEANY_HOME"
    return
  fi

  local xdg_home="${XDG_CONFIG_HOME:-$HOME/.config}/geany"
  local mac_home="$HOME/Library/Application Support/geany"

  case "$(uname -s 2>/dev/null || echo unknown)" in
    Darwin)
      if [[ -d "$xdg_home" ]]; then printf "%s\n" "$xdg_home"; fi
      if [[ -d "$mac_home" ]]; then printf "%s\n" "$mac_home"; fi
      if [[ ! -d "$xdg_home" && ! -d "$mac_home" ]]; then printf "%s\n" "$xdg_home"; fi
      ;;
    MINGW*|MSYS*|CYGWIN*)
      if [[ -n "${APPDATA:-}" ]]; then
        printf "%s\n" "$APPDATA/geany"
      else
        printf "%s\n" "$HOME/AppData/Roaming/geany"
      fi
      ;;
    *)
      printf "%s\n" "$xdg_home"
      ;;
  esac
}

err=0
checked=0

check_geany_home() {
  local geany_home="$1"
  local filedefs="$geany_home/filedefs/filetypes.vitte.conf"
  local ext_file="$geany_home/filetype_extensions.conf"
  local snippets_file="$geany_home/snippets.conf"

  if [[ ! -f "$filedefs" ]]; then
    echo "[geany-check][error] missing $filedefs" >&2
    err=1
  else
    grep -q "AUTO-GENERATED by tools/generate_editor_highlights.py" "$filedefs" || {
      echo "[geany-check][error] missing generated header in $filedefs" >&2
      err=1
    }
    grep -q "FT_00_CM=sh -lc 'vitte check " "$filedefs" || {
      echo "[geany-check][error] missing file check command in $filedefs" >&2
      err=1
    }
    grep -Eq '^FT_05_WD=%(d|p|c)$' "$filedefs" || {
      echo "[geany-check][error] missing/invalid project working dir token in $filedefs" >&2
      err=1
    }
  fi

  if [[ ! -f "$ext_file" ]]; then
    echo "[geany-check][error] missing $ext_file" >&2
    err=1
  else
    grep -Eq '^(Vitte|vitte)=.*\*\.vit' "$ext_file" || {
      echo "[geany-check][error] missing *.vit association in $ext_file" >&2
      err=1
    }
    grep -Eq '^(Vitte|vitte)=.*\*\.vitte' "$ext_file" || {
      echo "[geany-check][error] missing *.vitte association in $ext_file" >&2
      err=1
    }
  fi

  if [[ ! -f "$snippets_file" ]]; then
    echo "[geany-check][error] missing $snippets_file" >&2
    err=1
  else
    grep -Eq '^\[(vitte|Vitte)\]$' "$snippets_file" || {
      echo "[geany-check][error] missing [vitte]/[Vitte] snippets section in $snippets_file" >&2
      err=1
    }
    grep -q '^proc=' "$snippets_file" || {
      echo "[geany-check][error] missing proc snippet in $snippets_file" >&2
      err=1
    }
    grep -q '^role_contract=' "$snippets_file" || {
      echo "[geany-check][error] missing role_contract snippet in $snippets_file" >&2
      err=1
    }
  fi
}

while IFS= read -r geany_home; do
  [[ -n "$geany_home" ]] || continue
  checked=1
  check_geany_home "$geany_home"
done < <(detect_geany_homes)

if [[ "$checked" -eq 0 ]]; then
  echo "[geany-check][error] no Geany home detected" >&2
  err=1
fi

if [[ "$err" -ne 0 ]]; then
  exit 2
fi

echo "[geany-check] OK"
