#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GRAMMAR = ROOT / "editors/grammar/vitte_highlight_grammar.json"
GEANY_VERSION = "2.1"


def w(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    g = json.loads(GRAMMAR.read_text(encoding="utf-8"))
    keywords = g["keywords"]
    decls = g["decl_keywords"]
    types = g["types"]
    builtins = g["builtins"]
    todos = g["todos"]
    strict = g["strict_patterns"]

    kw = " ".join(keywords)
    decl = " ".join(decls)
    ty = " ".join(types)
    bi = " ".join(builtins)
    todo_alt = "|".join(todos)
    todo_alt_elisp = "\\|".join(todos)
    decl_alt = "|".join(decls)
    decl_alt_elisp = "\\\\|".join(decls)
    path_pattern = "[A-Za-z0-9_./:]+"
    module_directives = [k for k in ("space", "pull", "share", "at", "use") if k in keywords]
    module_alt = "|".join(module_directives)
    module_alt_elisp = "\\\\|".join(module_directives)
    api_alt = "|".join(f"{p}[A-Za-z0-9_]*" for p in strict["api_prefixes"])
    api_alt_elisp = "\\\\|".join(f"{p}[A-Za-z0-9_]*" for p in strict["api_prefixes"])

    vim_syntax = f'''" AUTO-GENERATED by tools/generate_editor_highlights.py; DO NOT EDIT
if exists("b:current_syntax")
  finish
endif

syn keyword vitteKeyword {kw}
syn keyword vitteDecl {decl}
syn keyword vitteType {ty}
syn keyword vitteBuiltin {bi}
syn keyword vitteTodo {' '.join(todos)}

syn match vitteNumber "\\v\\b(0x[0-9A-Fa-f]+|0b[01]+|[0-9]+(\\.[0-9]+)?)\\b"
syn region vitteString start=+"+ skip=+\\\\"+ end=+"+ contains=vitteEscape
syn match vitteChar "\\v'([^'\\\\]|\\\\.)'"
syn match vitteEscape "\\v\\\\([nrt0\\\"'\\\\]|x[0-9A-Fa-f]{{2}})" contained
syn match vitteUsePath "\\v\\<use\\>\\s+\\zs{path_pattern}"
syn match vitteModulePath "\\v\\<({module_alt})\\>\\s+\\zs{path_pattern}"
syn match vitteExport "\\v\\<export\\>\\s+\\zs(\\*|{path_pattern})"
syn match vitteDeclName "\\v\\<({decl_alt})\\>\\s+\\zs[A-Za-z_][A-Za-z0-9_]*"
syn match vitteSignatureType "\\v(:|->\\s*)\\s*\\zs[A-Za-z_][A-Za-z0-9_]*(\\[[A-Za-z_][A-Za-z0-9_]*\\])?"
syn match vitteUseAlias "\\v\\<as\\>\\s+\\zs[A-Za-z_][A-Za-z0-9_]*(_pkg)?"
syn match vitteConstructor "\\v\\<[A-Z][A-Za-z0-9_]*(\\.[A-Z][A-Za-z0-9_]*)*\\>"
syn match vitteConstant "\\v\\<[A-Z][A-Z0-9_]+\\>"
syn match vitteOperator "\\(->\\|=>\\|::\\|:=\\|==\\|!=\\|<=\\|>=\\|&&\\|[+*/%=<>!&|.-]\\)"
syn match vitteDelimiter "[][(){{}},;:]"
syn match vitteTrailingWhitespace "\\s\\+$"
syn match vitteDiagCode "\\v{strict['diag_code']}"
syn match vitteAliasPkg "\\v{strict['alias_pkg']}"
syn match vitteContractBlock "\\v^\\s*<<<\\s+ROLE-CONTRACT"
syn match vitteApiSurface "\\v\\<({api_alt})\\>"

syn region vitteLineComment start="//" end="$" contains=vitteTodo
syn region vitteHashComment start="#" end="$" contains=vitteTodo
syn region vitteBlockComment start="/\\*" end="\\*/" contains=vitteTodo
syn region vitteZoneComment start="<<<" end=">>>" contains=vitteTodo,vitteContractBlock

hi def link vitteKeyword Keyword
hi def link vitteDecl Statement
hi def link vitteType Type
hi def link vitteBuiltin Boolean
hi def link vitteNumber Number
hi def link vitteString String
hi def link vitteChar Character
hi def link vitteEscape SpecialChar
hi def link vitteUsePath Include
hi def link vitteModulePath Include
hi def link vitteExport Include
hi def link vitteDeclName Function
hi def link vitteSignatureType Type
hi def link vitteUseAlias Identifier
hi def link vitteConstructor Type
hi def link vitteConstant Constant
hi def link vitteOperator Operator
hi def link vitteDelimiter Delimiter
hi def link vitteTrailingWhitespace Error
hi def link vitteDiagCode Error
hi def link vitteAliasPkg Identifier
hi def link vitteContractBlock PreProc
hi def link vitteApiSurface Function
hi def link vitteTodo Todo
hi def link vitteLineComment Comment
hi def link vitteHashComment Comment
hi def link vitteBlockComment Comment
hi def link vitteZoneComment Comment

syn sync minlines=64

let b:current_syntax = "vitte"
'''
    w(ROOT / "editors/vim/syntax/vitte.vim", vim_syntax)

    vim_legacy = '" AUTO-GENERATED legacy entrypoint\nruntime! syntax/vitte.vim\n'
    w(ROOT / "editors/vim/vitte.vim", vim_legacy)

    vim_after = '''" AUTO-GENERATED strict overlay
hi def link vitteDiagCode DiagnosticError
hi def link vitteAliasPkg Special
hi def link vitteContractBlock Title
hi def link vitteApiSurface Special
'''
    w(ROOT / "editors/vim/after/syntax/vitte.vim", vim_after)

    vim_colors = '''" AUTO-GENERATED reference colorscheme
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "vitte_reference"

hi Statement ctermfg=81 guifg=#5fd7ff
hi Keyword ctermfg=75 guifg=#5fafff
hi Type ctermfg=110 guifg=#87afd7
hi Boolean ctermfg=149 guifg=#afd787
hi Number ctermfg=214 guifg=#ffaf00
hi String ctermfg=186 guifg=#d7d787
hi Include ctermfg=215 guifg=#ffaf5f
hi Error ctermfg=203 guifg=#ff5f5f
hi Identifier ctermfg=159 guifg=#afffff
hi Title ctermfg=222 guifg=#ffd787
hi Function ctermfg=117 guifg=#87d7ff
hi Todo ctermfg=196 guifg=#ff0000
hi Comment ctermfg=244 guifg=#808080
'''
    w(ROOT / "editors/vim/colors/vitte_reference.vim", vim_colors)

    w(ROOT / "editors/vim/ftdetect/vitte.vim", "au BufRead,BufNewFile *.vit,*.vitte,*.vitl set filetype=vitte\n")

    vim_ftplugin = r'''" AUTO-GENERATED vitte ftplugin
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

setlocal shiftwidth=2
setlocal tabstop=2
setlocal softtabstop=2
setlocal expandtab
setlocal commentstring=//\ %s
setlocal comments=s1:/*,mb:*,ex:*/,://,b:#
setlocal suffixesadd=.vit,.vitte,.vitl
setlocal makeprg=vitte\ check\ %
setlocal formatprg=vitte\ fmt\ -

if exists(":compiler") == 2
  compiler vitte
endif

let b:undo_ftplugin = "setlocal shiftwidth< tabstop< softtabstop< expandtab< commentstring< comments< suffixesadd< makeprg< formatprg<"
'''
    w(ROOT / "editors/vim/ftplugin/vitte.vim", vim_ftplugin)

    emacs_mode = f''';;; vitte-mode.el --- Major mode for Vitte (generated) -*- lexical-binding: t; -*-

(defgroup vitte nil "Vitte language support." :group 'languages)

(declare-function vitte-indent-line "vitte-indent")

(defcustom vitte-binary
  (or (executable-find "vitte") "vitte")
  "Path to the Vitte binary used by helper commands."
  :type 'string
  :group 'vitte)

(defvar vitte-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-c") #'vitte-check-buffer)
    (define-key map (kbd "C-c C-b") #'vitte-build-buffer)
    (define-key map (kbd "C-c C-p") #'vitte-parse-buffer)
    map)
  "Keymap for `vitte-mode'.")

(defvar vitte-mode-syntax-table
  (let ((st (make-syntax-table)))
    (modify-syntax-entry ?_ "w" st)
    (modify-syntax-entry ?/ ". 124b" st)
    (modify-syntax-entry ?* ". 23" st)
    (modify-syntax-entry ?\\n ">" st)
    (modify-syntax-entry ?\\" "\\\"" st)
    st)
  "Syntax table for `vitte-mode'.")

(defface vitte-diag-face
  '((t :inherit font-lock-warning-face :weight bold))
  "Face for VITTE diagnostics codes.")

(defface vitte-alias-face
  '((t :inherit font-lock-variable-name-face :slant italic))
  "Face for *_pkg aliases.")

(defface vitte-contract-face
  '((t :inherit font-lock-preprocessor-face :weight bold))
  "Face for ROLE-CONTRACT headers.")

(defconst vitte-keywords '({" ".join('"'+k+'"' for k in keywords)}))
(defconst vitte-decls '({" ".join('"'+k+'"' for k in decls)}))
(defconst vitte-types '({" ".join('"'+t+'"' for t in types)}))
(defconst vitte-builtins '({" ".join('"'+b+'"' for b in builtins)}))

(defvar vitte-font-lock-keywords
  `((,(regexp-opt vitte-keywords 'symbols) . font-lock-keyword-face)
    (,(regexp-opt vitte-decls 'symbols) . font-lock-function-name-face)
    (,(regexp-opt vitte-types 'symbols) . font-lock-type-face)
    (,(regexp-opt vitte-builtins 'symbols) . font-lock-constant-face)
    ("\\\\<\\\\({decl_alt_elisp}\\\\)\\\\>\\\\s-+\\\\([A-Za-z_][A-Za-z0-9_]*\\\\)" 2 font-lock-function-name-face)
    ("\\\\<\\\\({module_alt_elisp}\\\\)\\\\>\\\\s-+\\\\({path_pattern}\\\\)" 2 font-lock-constant-face)
    ("\\\\<as\\\\>\\\\s-+\\\\([A-Za-z_][A-Za-z0-9_]*\\\\(?:_pkg\\\\)?\\\\)" 1 'vitte-alias-face)
    ("'\\\\([^'\\\\\\\\]\\\\|\\\\\\\\.\\\\)'" . font-lock-string-face)
    ("\\\\<[A-Za-z_][A-Za-z0-9_]*_pkg\\\\>" . 'vitte-alias-face)
    ("\\\\<VITTE-[A-Z]+[0-9]\\\\{{4\\\\}}\\\\>" . 'vitte-diag-face)
    ("^\\\\s-*<<<\\\\s-+ROLE-CONTRACT" . 'vitte-contract-face)
    ("\\\\<\\\\({api_alt_elisp}\\\\)\\\\>" . font-lock-builtin-face)
    ("\\\\<\\\\({todo_alt_elisp}\\\\)\\\\>" . font-lock-warning-face)
    ("\\\\<use\\\\>\\\\s-+\\\\({path_pattern}\\\\)" 1 font-lock-constant-face)))

(defvar vitte-imenu-generic-expression
  '(("proc" "^\\\\s-*proc\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("form" "^\\\\s-*form\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("pick" "^\\\\s-*pick\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("trait" "^\\\\s-*trait\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("entry" "^\\\\s-*entry\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)))

(defun vitte--completion-at-point ()
  (let ((bounds (bounds-of-thing-at-point 'symbol)))
    (when bounds
      (list (car bounds)
            (cdr bounds)
            (append vitte-keywords vitte-decls vitte-types vitte-builtins)
            :exclusive 'no))))

(defun vitte--file-or-error ()
  (or (buffer-file-name) (user-error "Buffer is not visiting a file")))

(defun vitte--run (subcommand file)
  (compile (format "%s %s %s"
                   (shell-quote-argument vitte-binary)
                   subcommand
                   (shell-quote-argument file))))

(defun vitte-check-buffer () (interactive) (vitte--run "check" (vitte--file-or-error)))
(defun vitte-build-buffer () (interactive) (vitte--run "build" (vitte--file-or-error)))
(defun vitte-parse-buffer () (interactive) (vitte--run "parse" (vitte--file-or-error)))

;;;###autoload
(define-derived-mode vitte-mode prog-mode "Vitte"
  "Major mode for editing Vitte source files."
  :keymap vitte-mode-map
  :syntax-table vitte-mode-syntax-table
  (setq font-lock-defaults '(vitte-font-lock-keywords))
  (setq-local comment-start "// ")
  (setq-local comment-end "")
  (setq-local comment-start-skip "//+\\\\s-*")
  (setq-local comment-use-syntax t)
  (setq-local imenu-generic-expression vitte-imenu-generic-expression)
  (add-hook 'completion-at-point-functions #'vitte--completion-at-point nil t)
  (when (require 'vitte-indent nil t)
    (setq-local indent-line-function #'vitte-indent-line)))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\\\.\\(vit\\|vitte\\)\\\\'" . vitte-mode))

(provide 'vitte-mode)
;;; vitte-mode.el ends here
'''
    w(ROOT / "editors/emacs/vitte-mode.el", emacs_mode)

    nano = f'''## AUTO-GENERATED by tools/generate_editor_highlights.py; DO NOT EDIT
syntax "vitte" "\\.vit$" "\\.vitte$" "\\.vitl$"
comment "// "
tabgives "  "

# Keywords and declarations
color brightcyan "\\<({'|'.join(keywords)})\\>"
color white,blue "\\<({'|'.join(decls)})\\>"
color brightblue "^[[:space:]]*({decl_alt})[[:space:]]+[A-Za-z_][A-Za-z0-9_]*"
color cyan "\\<(export)\\>[[:space:]]+[*A-Za-z0-9_./:]+"

# Types and builtins
color brightblue "\\<({'|'.join(types)})\\>"
color brightgreen "\\<({'|'.join(builtins)})\\>"
color brightblue "(:|->[[:space:]]*)[[:space:]]*[A-Za-z_][A-Za-z0-9_]*(\\[[A-Za-z_][A-Za-z0-9_]*\\])?"
color magenta "\\<[A-Z][A-Za-z0-9_]*(\\.[A-Z][A-Za-z0-9_]*)*\\>"
color magenta "\\<[A-Z][A-Z0-9_]+\\>"

# Strict highlights
color red "\\<VITTE-[A-Z]+[0-9]{{4}}\\>"
color magenta "\\<[A-Za-z_][A-Za-z0-9_]*_pkg\\>"
color brightyellow "^\\s*<<<\\s+ROLE-CONTRACT"
color cyan "\\<((diagnostics_|quickfix_|doctor_)[A-Za-z0-9_]*)\\>"

# Literals and paths
color brightmagenta "\\<(0x[0-9A-Fa-f]+|0b[01]+|[0-9]+(\\.[0-9]+)?)\\>"
color yellow start="\\\"" end="\\\""
color yellow start="'" end="'"
color cyan "\\<({module_alt})\\>\\s+({path_pattern})"
color brightblue "\\<({decl_alt})\\>\\s+([A-Za-z_][A-Za-z0-9_]*)"
color magenta "\\<as\\>\\s+([A-Za-z_][A-Za-z0-9_]*(_pkg)?)"
color brightcyan "\\<[A-Za-z_][A-Za-z0-9_]*\\("

# Operators, punctuation, and editor cues
color brightyellow "(->|=>|::|:=|==|!=|<=|>=|&&|\\|\\||[+*/%=<>!&|.-])"
color normal "[(){{}}\\[\\],;:]"
color ,red "[[:space:]]+$"

# Comments
color brightblack "//.*$"
color brightblack "#.*$"
color brightblack start="/\\*" end="\\*/"
color brightblack start="<<<" end=">>>"

# TODOs
color red "\\<({todo_alt})\\>"
'''
    w(ROOT / "editors/nano/vitte.nanorc", nano)

    geany_symbol_re = "^[[:space:]]*(proc|form|pick|trait|entry|macro|type|field|case|const)[[:space:]]+[A-Za-z_][A-Za-z0-9_]*|^[[:space:]]*(space|use|pull|share)[[:space:]]+[A-Za-z0-9_./:]+|^[[:space:]]*<<<[[:space:]]+ROLE-CONTRACT|VITTE-[A-Z]+[0-9][0-9][0-9][0-9]|(diagnostics_|quickfix_|doctor_)[A-Za-z0-9_]+|[A-Za-z_][A-Za-z0-9_]*_pkg"
    geany_find_vitte = '/usr/bin/find . -type f \\( -name "*.vit" -o -name "*.vitte" -o -name "*.vitl" \\) -print0'

    geany_cfg = f'''# AUTO-GENERATED by tools/generate_editor_highlights.py v{GEANY_VERSION}; DO NOT EDIT
# Vitte language support for Geany
# Install to: ~/.config/geany/filedefs/filetypes.vitte.conf

[styling]
lexer_filetype=C

# High-contrast palette tuned for Geany's C lexer.
default=#111111;;false;false
comment=#0b7a0b;;false;true
commentline=#0b7a0b;;false;true
commentdoc=#0b7a0b;;false;true
number=#0a7f66;;false;false
word=#0033cc;;true;false
word2=#7a3e9d;;false;false
string=#a31515;;false;false
character=#a31515;;false;false
uuid=#0a7f66;;false;false
preprocessor=#7a3e9d;;false;false
operator=#202020;;false;false
identifier=#111111;;false;false
stringeol=#d10000;;true;false
verbatim=#a31515;;false;false
regex=#c41a16;;false;false
commentlinedoc=#0b7a0b;;false;true
word3=#1f4e79;;false;false
word4=#7a3e9d;;false;false
word5=#005a9e;;false;false
word6=#0a7f66;;false;false
word7=#8a6d1d;;false;false
word8=#333333;;false;false
commentdockeyword=#0033cc;;true;false
commentdockeyworderror=#d10000;;true;false
globalclass=#7a3e9d;;false;false

[keywords]
primary={' '.join(keywords)}
secondary={' '.join(decls)} {' '.join(builtins)} export ROLE-CONTRACT INVARIANT AUDIT TODO VITTE-H0001 diagnostics_ quickfix_ doctor_ core_pkg
docComment={' '.join(todos)}
typedefs={' '.join(types)}

[settings]
extension=vit
wordchars=_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-
lexer_filetype=C
tag_parser=C
symbol_list_sort_mode=1
comment_single=//
comment_open=/*
comment_close=*/
comment_use_indent=true
context_action_cmd=sh -lc 'vitte check "$1"' sh "%f"

[indentation]
width=2
type=1
hard_tab_width=8
detect_indent=false
detect_indent_width=false
indent_mode=2

[build-menu]
# Robust quoting via sh -lc keeps behavior stable with spaces in paths.
FT_00_LB=_Check
FT_00_CM=sh -lc 'vitte check "$1"' sh "%f"
FT_00_WD=%d
FT_01_LB=_Build
FT_01_CM=sh -lc 'vitte build "$1"' sh "%f"
FT_01_WD=%d
FT_02_LB=_Run
FT_02_CM=sh -lc 'vitte run "$1"' sh "%f"
FT_02_WD=%d
FT_03_LB=_Test
FT_03_CM=sh -lc 'vitte test "$1"' sh "%p"
FT_03_WD=%p
FT_04_LB=F_ormat
FT_04_CM=sh -lc 'vitte fmt "$1"' sh "%f"
FT_04_WD=%d
FT_05_LB=_Parse
FT_05_CM=sh -lc 'vitte parse "$1"' sh "%f"
FT_05_WD=%d
FT_06_LB=Project _Check
FT_06_CM=sh -lc 'if [ -f Makefile ]; then make quickstart-check; else vitte check "$1"; fi' sh "%f"
FT_06_WD=%p
FT_07_LB=Project T_est
FT_07_CM=sh -lc 'if [ -f Makefile ]; then vitte test .; else vitte test "$1"; fi' sh "%f"
FT_07_WD=%p
FT_08_LB=Project F_ormat
FT_08_CM=sh -lc 'if [ -f Makefile ]; then make fmt 2>/dev/null || vitte fmt .; else vitte fmt "$1"; fi' sh "%f"
FT_08_WD=%p
FT_09_LB=Project _Clean
FT_09_CM=sh -lc 'if [ -f Makefile ]; then make clean; else echo "No Makefile in project root"; fi' sh
FT_09_WD=%p
EX_00_LB=_Current File Symbols
EX_00_CM=sh -lc '/usr/bin/grep -nE "{geany_symbol_re}" "$1" || echo "No Vitte symbols detected"' sh "%f"
EX_00_WD=%d
EX_01_LB=_Workspace Symbols
EX_01_CM=sh -lc '{geany_find_vitte} | /usr/bin/xargs -0 /usr/bin/grep -nHE "{geany_symbol_re}" || echo "No Vitte symbols detected in workspace"' sh
EX_01_WD=%p
EX_02_LB=_Diagnostics
EX_02_CM=sh -lc 'vitte check "$1"' sh "%f"
EX_02_WD=%d
EX_03_LB=_Package Manifest
EX_03_CM=sh -lc 'if [ -f vitte.pkg ] || [ -f package.vit ] || [ -f steelconf ]; then ls -la vitte.pkg package.vit steelconf 2>/dev/null; else echo "No Vitte package manifest detected"; fi' sh
EX_03_WD=%p
EX_04_LB=Quickstart _Check (Makefile)
EX_04_CM=sh -lc 'if [ -f Makefile ]; then make quickstart-check; else echo "No Makefile in project root"; fi' sh
EX_04_WD=%p
EX_05_LB=Core _Language Gate (Makefile)
EX_05_CM=sh -lc 'if [ -f Makefile ]; then make core-language-gate; else echo "No Makefile in project root"; fi' sh
EX_05_WD=%p
EX_06_LB=_List Vitte Files
EX_06_CM=sh -lc '{geany_find_vitte} | /usr/bin/xargs -0 -r printf "%s\\n"' sh
EX_06_WD=%p
EX_07_LB=_Version
EX_07_CM=sh -lc 'vitte --version'
EX_07_WD=%p

# Optional mono/multi-root overrides:
# - project-root mode: set *_WD=%p
# - current-file dir mode: set *_WD=%d
# - current process dir mode: set *_WD=%c
'''
    w(ROOT / "editors/geany/filetypes.vitte.conf", geany_cfg)

    print("[generate-editor-highlights] wrote vim/emacs/nano/geany assets (tree-sitter queries are maintained separately)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
