#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GRAMMAR = ROOT / "editors/grammar/vitte_highlight_grammar.json"


def w(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    g = json.loads(GRAMMAR.read_text(encoding="utf-8"))
    keywords = g["keywords"]
    decls = g["decl_keywords"]
    types = g["types"]
    builtins = g["builtins"]
    todos = g["todos"]
    strict = g["strict_patterns"]

    kw = " ".join(keywords)
    decl = " ".join(decls)
    ty = " ".join(types)
    bi = " ".join(builtins)
    todo_alt = "|".join(todos)

    vim_syntax = f'''" AUTO-GENERATED by tools/generate_editor_highlights.py; DO NOT EDIT
if exists("b:current_syntax")
  finish
endif

syn keyword vitteKeyword {kw}
syn keyword vitteDecl {decl}
syn keyword vitteType {ty}
syn keyword vitteBuiltin {bi}
syn keyword vitteTodo {' '.join(todos)}

syn match vitteNumber "\\v{g['number_regex']}"
syn region vitteString start=+"+ skip=+\\\\"+ end=+"+
syn match vitteUsePath "\\v\\<use\\>\\s+\\zs[A-Za-z0-9_./]+"
syn match vitteDiagCode "\\v{strict['diag_code']}"
syn match vitteAliasPkg "\\v{strict['alias_pkg']}"
syn match vitteContractBlock "\\v^\\s*<<<\\s+ROLE-CONTRACT"
syn match vitteApiSurface "\\v\\<(diagnostics_[A-Za-z0-9_]*|quickfix_[A-Za-z0-9_]*|doctor_[A-Za-z0-9_]*)\\>"

syn region vitteLineComment start="//" end="$" contains=vitteTodo
syn region vitteBlockComment start="/\\*" end="\\*/" contains=vitteTodo
syn region vitteZoneComment start="<<<" end=">>>" contains=vitteTodo,vitteContractBlock

hi def link vitteKeyword Keyword
hi def link vitteDecl Statement
hi def link vitteType Type
hi def link vitteBuiltin Boolean
hi def link vitteNumber Number
hi def link vitteString String
hi def link vitteUsePath Include
hi def link vitteDiagCode Error
hi def link vitteAliasPkg Identifier
hi def link vitteContractBlock PreProc
hi def link vitteApiSurface Function
hi def link vitteTodo Todo
hi def link vitteLineComment Comment
hi def link vitteBlockComment Comment
hi def link vitteZoneComment Comment

let b:current_syntax = "vitte"
'''
    w(ROOT / "editors/vim/syntax/vitte.vim", vim_syntax)

    vim_legacy = '" AUTO-GENERATED legacy entrypoint\nruntime! syntax/vitte.vim\n'
    w(ROOT / "editors/vim/vitte.vim", vim_legacy)

    vim_after = '''" AUTO-GENERATED strict overlay
hi def link vitteDiagCode DiagnosticError
hi def link vitteAliasPkg Special
hi def link vitteContractBlock Title
hi def link vitteApiSurface Special
'''
    w(ROOT / "editors/vim/after/syntax/vitte.vim", vim_after)

    vim_colors = '''" AUTO-GENERATED reference colorscheme
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "vitte_reference"

hi Statement ctermfg=81 guifg=#5fd7ff
hi Keyword ctermfg=75 guifg=#5fafff
hi Type ctermfg=110 guifg=#87afd7
hi Boolean ctermfg=149 guifg=#afd787
hi Number ctermfg=214 guifg=#ffaf00
hi String ctermfg=186 guifg=#d7d787
hi Include ctermfg=215 guifg=#ffaf5f
hi Error ctermfg=203 guifg=#ff5f5f
hi Identifier ctermfg=159 guifg=#afffff
hi Title ctermfg=222 guifg=#ffd787
hi Function ctermfg=117 guifg=#87d7ff
hi Todo ctermfg=196 guifg=#ff0000
hi Comment ctermfg=244 guifg=#808080
'''
    w(ROOT / "editors/vim/colors/vitte_reference.vim", vim_colors)

    w(ROOT / "editors/vim/ftdetect/vitte.vim", "au BufRead,BufNewFile *.vit set filetype=vitte\n")

    vim_ftplugin = r'''" AUTO-GENERATED vitte ftplugin
if exists("b:did_ftplugin")
  finish
endif
let b:did_ftplugin = 1

setlocal shiftwidth=2
setlocal tabstop=2
setlocal softtabstop=2
setlocal expandtab
setlocal commentstring=//\ %s
setlocal omnifunc=syntaxcomplete#Complete
setlocal makeprg=vitte\ check\ %

let b:undo_ftplugin = "setlocal shiftwidth< tabstop< softtabstop< expandtab< commentstring< omnifunc< makeprg<"
'''
    w(ROOT / "editors/vim/ftplugin/vitte.vim", vim_ftplugin)

    emacs_mode = f''';;; vitte-mode.el --- Major mode for Vitte (generated) -*- lexical-binding: t; -*-

(defgroup vitte nil "Vitte language support." :group 'languages)

(defcustom vitte-binary
  (or (executable-find "vitte") "vitte")
  "Path to the Vitte binary used by helper commands."
  :type 'string
  :group 'vitte)

(defvar vitte-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-c") #'vitte-check-buffer)
    (define-key map (kbd "C-c C-b") #'vitte-build-buffer)
    (define-key map (kbd "C-c C-p") #'vitte-parse-buffer)
    map)
  "Keymap for `vitte-mode'.")

(defvar vitte-mode-syntax-table
  (let ((st (make-syntax-table)))
    (modify-syntax-entry ?_ "w" st)
    (modify-syntax-entry ?/ ". 124b" st)
    (modify-syntax-entry ?* ". 23" st)
    (modify-syntax-entry ?\\n ">" st)
    (modify-syntax-entry ?\\" "\\\"" st)
    st)
  "Syntax table for `vitte-mode'.")

(defface vitte-diag-face
  '((t :inherit font-lock-warning-face :weight bold))
  "Face for VITTE diagnostics codes.")

(defface vitte-alias-face
  '((t :inherit font-lock-variable-name-face :slant italic))
  "Face for *_pkg aliases.")

(defface vitte-contract-face
  '((t :inherit font-lock-preprocessor-face :weight bold))
  "Face for ROLE-CONTRACT headers.")

(defconst vitte-keywords '({" ".join('"'+k+'"' for k in keywords)}))
(defconst vitte-decls '({" ".join('"'+k+'"' for k in decls)}))
(defconst vitte-types '({" ".join('"'+t+'"' for t in types)}))
(defconst vitte-builtins '({" ".join('"'+b+'"' for b in builtins)}))

(defvar vitte-font-lock-keywords
  `((,(regexp-opt vitte-keywords 'symbols) . font-lock-keyword-face)
    (,(regexp-opt vitte-decls 'symbols) . font-lock-function-name-face)
    (,(regexp-opt vitte-types 'symbols) . font-lock-type-face)
    (,(regexp-opt vitte-builtins 'symbols) . font-lock-constant-face)
    ("\\\\<[A-Za-z_][A-Za-z0-9_]*_pkg\\\\>" . 'vitte-alias-face)
    ("\\\\<VITTE-[A-Z]+[0-9]\\\\{{4\\\\}}\\\\>" . 'vitte-diag-face)
    ("^\\\\s-*<<<\\\\s-+ROLE-CONTRACT" . 'vitte-contract-face)
    ("\\\\<\\\\(diagnostics_[A-Za-z0-9_]*\\\\|quickfix_[A-Za-z0-9_]*\\\\|doctor_[A-Za-z0-9_]*\\\\)\\\\>" . font-lock-builtin-face)
    ("\\\\<\\\\({todo_alt}\\\\)\\\\>" . font-lock-warning-face)
    ("\\\\<use\\\\>\\\\s-+\\\\([A-Za-z0-9_./]+\\\\)" 1 font-lock-constant-face)))

(defvar vitte-imenu-generic-expression
  '(("proc" "^\\\\s-*proc\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("form" "^\\\\s-*form\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("pick" "^\\\\s-*pick\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("trait" "^\\\\s-*trait\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)
    ("entry" "^\\\\s-*entry\\\\s-+\\\\([A-Za-z0-9_]+\\\\)" 1)))

(defun vitte--completion-at-point ()
  (let ((bounds (bounds-of-thing-at-point 'symbol)))
    (when bounds
      (list (car bounds)
            (cdr bounds)
            (append vitte-keywords vitte-decls vitte-types vitte-builtins)
            :exclusive 'no))))

(defun vitte--file-or-error ()
  (or (buffer-file-name) (user-error "Buffer is not visiting a file")))

(defun vitte--run (subcommand file)
  (compile (format "%s %s %s"
                   (shell-quote-argument vitte-binary)
                   subcommand
                   (shell-quote-argument file))))

(defun vitte-check-buffer () (interactive) (vitte--run "check" (vitte--file-or-error)))
(defun vitte-build-buffer () (interactive) (vitte--run "build" (vitte--file-or-error)))
(defun vitte-parse-buffer () (interactive) (vitte--run "parse" (vitte--file-or-error)))

;;;###autoload
(define-derived-mode vitte-mode prog-mode "Vitte"
  "Major mode for editing Vitte source files."
  :keymap vitte-mode-map
  :syntax-table vitte-mode-syntax-table
  (setq font-lock-defaults '(vitte-font-lock-keywords))
  (setq-local comment-start "// ")
  (setq-local comment-end "")
  (setq-local comment-start-skip "//+\\\\s-*")
  (setq-local comment-use-syntax t)
  (setq-local imenu-generic-expression vitte-imenu-generic-expression)
  (add-hook 'completion-at-point-functions #'vitte--completion-at-point nil t)
  (when (require 'vitte-indent nil t)
    (setq-local indent-line-function #'vitte-indent-line))
  (when (require 'lsp-mode nil t)
    (add-hook 'vitte-mode-hook #'lsp-deferred nil t)))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\\\.vit\\\\'" . vitte-mode))

(provide 'vitte-mode)
;;; vitte-mode.el ends here
'''
    w(ROOT / "editors/emacs/vitte-mode.el", emacs_mode)

    nano = f'''## AUTO-GENERATED by tools/generate_editor_highlights.py; DO NOT EDIT
syntax "vitte" "\\.vit$"

# Keywords and declarations
color brightcyan "\\<({'|'.join(keywords)})\\>"
color white,blue "\\<({'|'.join(decls)})\\>"

# Types and builtins
color brightblue "\\<({'|'.join(types)})\\>"
color brightgreen "\\<({'|'.join(builtins)})\\>"

# Strict highlights
color red "\\<VITTE-[A-Z]+[0-9]{{4}}\\>"
color magenta "\\<[A-Za-z_][A-Za-z0-9_]*_pkg\\>"
color brightyellow "^\\s*<<<\\s+ROLE-CONTRACT"
color cyan "\\<((diagnostics_|quickfix_|doctor_)[A-Za-z0-9_]*)\\>"

# Numbers and strings
color brightmagenta "\\<([0-9]+|0x[0-9A-Fa-f]+|0b[01]+)\\>"
color yellow "\"([^\"\\\\]|\\\\.)*\""

# Comments
color brightblack "//.*$"
color brightblack start="/\\*" end="\\*/"
color brightblack start="<<<" end=">>>"

# TODOs
color red "\\<({todo_alt})\\>"
'''
    w(ROOT / "editors/nano/vitte.nanorc", nano)

    print("[generate-editor-highlights] wrote vim/emacs/nano assets (tree-sitter queries are maintained separately)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
