#!/usr/bin/env python3
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
DOC_PATH = ROOT / "docs" / "MAKE_TARGETS.md"

SECTIONS: list[tuple[str, list[str]]] = [
    (
        "Beginner / Local Loop",
        [
            "build",
            "quickstart-check",
            "doctor",
            "test",
            "parse",
            "hir-validate",
        ],
    ),
    (
        "Core Language",
        [
            "grammar-check",
            "grammar-gate",
            "core-language-gate",
            "core-release-gate",
        ],
    ),
    (
        "Modules / Packages",
        [
            "modules-tests",
            "modules-snapshots",
            "modules-contract-snapshots",
            "packages-gate",
        ],
    ),
    (
        "CI / Reports",
        [
            "ci-fast",
            "ci-strict",
            "ci-completions",
            "repo-hygiene-check",
            "docs-paths-check",
            "dx-adoption",
            "public-benchmark-dashboard",
            "release-proof-notes",
            "all-tests",
            "reports-index",
            "release-doctor",
        ],
    ),
    (
        "VitteOS",
        [
            "vitteos-doctor",
            "vitteos-quick",
            "vitteos-ci",
            "vitteos-ci-strict",
        ],
    ),
    (
        "Packaging",
        [
            "pkg-debian",
            "pkg-debian-audit",
            "pkg-macos",
            "release-check",
        ],
    ),
]


def read_make_help() -> str:
    out = subprocess.check_output(["make", "help"], cwd=ROOT, text=True)
    return out


def parse_help_targets(help_text: str) -> dict[str, str]:
    targets: dict[str, str] = {}
    pattern = re.compile(r"^\s*make\s+([a-zA-Z0-9_.-]+)\s+(.*)$")
    for line in help_text.splitlines():
        m = pattern.match(line)
        if not m:
            continue
        target, description = m.group(1), m.group(2).strip()
        targets[target] = description
    return targets


def render_doc(targets: dict[str, str]) -> str:
    lines: list[str] = [
        "# Make Targets",
        "",
        "This page indexes the most useful `make` entrypoints.",
        "",
        "For the full list, run:",
        "",
        "```sh",
        "make help",
        "```",
        "",
        "<!-- AUTO-GENERATED by tools/generate_make_targets_doc.py -->",
        "",
    ]
    for title, names in SECTIONS:
        lines.append(f"## {title}")
        lines.append("")
        for name in names:
            description = targets[name]
            lines.append(f"- `make {name}`: {description}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    help_text = read_make_help()
    known_targets = parse_help_targets(help_text)

    missing = []
    for _, names in SECTIONS:
        for name in names:
            if name not in known_targets:
                missing.append(name)
    if missing:
        print(
            "[make-targets-doc][error] missing targets in `make help`: "
            + ", ".join(sorted(missing)),
            file=sys.stderr,
        )
        return 2

    rendered = render_doc(known_targets)
    if args.check:
        current = DOC_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "[make-targets-doc][error] docs/MAKE_TARGETS.md is out of date; "
                "run: make make-targets-doc",
                file=sys.stderr,
            )
            return 1
        print("[make-targets-doc] OK")
        return 0

    DOC_PATH.write_text(rendered, encoding="utf-8")
    print("[make-targets-doc] wrote docs/MAKE_TARGETS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
