#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "tests" / "explain_snapshots"
sys.path.insert(0, str(ROOT / "tools"))
from diagnostic_catalog_data import diagnostic_family, explanation_fields, readable_from_code
from diagnostics_locales import SUPPORTED_DIAGNOSTIC_LOCALES, supported_locale_codes

REPRESENTATIVE_CODES = (
    "E0001",
    "TYPECK_E_ASSIGN_MISMATCH",
    "BORROWCK_E_USE_AFTER_MOVE",
)

FALLBACK_CASES = (
    ("E0001", "xx-YY", "fallback_unknown_locale"),
    ("NO_SUCH_CODE", "en", "fallback_unknown_code"),
    ("E0001", "fr-FR", "alias_fr_FR"),
    ("E0001", "es-MX", "alias_es_MX"),
    ("E0001", "zh_CN", "alias_zh_CN"),
)

UNKNOWN_CODE_FIELDS = {
    "message": "diagnostic code is known by the full catalog when available",
    "summary": "The bootstrap compiler can explain core diagnostics and leaves other codes to the generated catalog.",
    "cause": "This seed runtime carries a compact fallback catalog.",
    "typical": "diagnostic generated by a newer catalog; local snapshot using a code absent from this seed runtime",
    "step1": "Run the full compiler build for the complete localized explanation.",
    "correction": "Use bin/vitte when a host compiler exists, otherwise keep this code for support.",
    "pitfalls": "do not rename the code before checking the central diagnostic catalog",
    "fix": "Use bin/vitte when a host compiler exists, otherwise keep this code for support.",
    "invalid_example": "vitte explain NO_SUCH_CODE --lang {locale}",
    "valid_example": "vitte explain {code} --lang {locale}",
}


def parse_ftl(path: Path) -> dict[str, str]:
    messages: dict[str, str] = {}
    if not path.exists():
        return messages
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        messages[key.strip()] = value.strip()
    return messages


def normalize_locale(lang: str) -> str:
    if not lang:
        return "en"
    for locale in SUPPORTED_DIAGNOSTIC_LOCALES:
        if lang == locale.code or lang in locale.aliases:
            return locale.code
    return "en"


def phase_from_code(code: str) -> str:
    if code == "NO_SUCH_CODE":
        return "diagnostics"
    family = diagnostic_family(code)
    if family == "syntax":
        return "parser"
    if family == "type checking":
        return "typeck"
    if family == "ownership":
        return "borrowck"
    if family == "name and module analysis":
        return "sema"
    return family.replace(" ", "-")


def explain_fields(code: str, locale: str) -> dict[str, str]:
    if code == "NO_SUCH_CODE":
        return {
            **UNKNOWN_CODE_FIELDS,
            "invalid_example": UNKNOWN_CODE_FIELDS["invalid_example"].format(locale=locale),
            "valid_example": UNKNOWN_CODE_FIELDS["valid_example"].format(code=code, locale=locale),
            "example": f"vitte explain {code} --lang {locale}",
        }

    messages = parse_ftl(ROOT / "locales" / locale / "diagnostics.ftl")
    en_messages = parse_ftl(ROOT / "locales" / "en" / "diagnostics.ftl")
    explain = parse_ftl(ROOT / "locales" / locale / "diagnostics_explain.ftl")
    message = messages.get(code, en_messages.get(code, readable_from_code(code)))
    fallback = explanation_fields(code, message)
    family = diagnostic_family(code)
    extra = {
        "typical": "minimal invalid source; generated source missing the same contract",
        "pitfalls": "avoid changing unrelated code while fixing the highlighted contract",
        "invalid_example": f"vitte check invalid-{code}.vit",
        "valid_example": fallback["example"],
    }
    if family == "syntax":
        extra = {
            "typical": "missing name after a declaration keyword; incomplete binding; truncated import path",
            "pitfalls": "do not add a placeholder name that is not used by the surrounding construct",
            "invalid_example": "proc () -> int { give 0 }",
            "valid_example": fallback["example"],
        }
        if code == "E0001" and locale == "fr":
            extra["typical"] = "nom manquant apres un mot-cle de declaration; liaison incomplete; chemin d'import tronque"
            extra["pitfalls"] = "n'ajoutez pas un nom factice qui ne correspond pas a la construction autour"
    elif family == "type checking":
        extra = {
            "typical": "assigning a string to an integer binding; reusing a value with a narrower annotation; returning a value through a mismatched slot",
            "pitfalls": "do not silence the error by widening the declaration when callers require the original type",
            "invalid_example": 'let count: int = "one"',
            "valid_example": fallback["example"],
        }
    elif family == "ownership":
        extra = {
            "typical": "passing ownership to another procedure and reading the original binding later; moving a field then using the parent; keeping an alias after ownership transfer",
            "pitfalls": "do not keep references that outlive the moved owner",
            "invalid_example": "let moved = value; give value",
            "valid_example": fallback["example"],
        }
    return {
        "message": message,
        "summary": explain.get(f"{code}.summary", fallback["summary"]),
        "cause": explain.get(f"{code}.cause", fallback["cause"]),
        "typical": explain.get(f"{code}.typical", extra["typical"]),
        "step1": explain.get(f"{code}.step1", fallback["step1"]),
        "correction": explain.get(f"{code}.correction", explain.get(f"{code}.fix", fallback["fix"])),
        "pitfalls": explain.get(f"{code}.pitfalls", extra["pitfalls"]),
        "fix": explain.get(f"{code}.fix", fallback["fix"]),
        "example": explain.get(f"{code}.example", fallback["example"]),
        "invalid_example": explain.get(f"{code}.invalid_example", extra["invalid_example"]),
        "valid_example": explain.get(f"{code}.valid_example", explain.get(f"{code}.example", extra["valid_example"])),
    }


def render(code: str, lang: str) -> str:
    locale = normalize_locale(lang)
    fields = explain_fields(code, locale)
    return "\n".join(
        [
            f"error code: {code}",
            f"lang: {locale}",
            f"phase: {phase_from_code(code)}",
            f"message: {fields['message']}",
            f"summary: {fields['summary']}",
            f"cause: {fields['cause']}",
            f"typical cases: {fields['typical']}",
            f"step 1: {fields['step1']}",
            f"correction: {fields['correction']}",
            f"common pitfalls: {fields['pitfalls']}",
            f"fix: {fields['fix']}",
            f"example: {fields['example']}",
            f"invalid example: {fields['invalid_example']}",
            f"valid example: {fields['valid_example']}",
            "",
        ]
    )


def snapshot_name(code: str, lang: str, label: str | None = None) -> str:
    if label:
        return label
    return f"{code}.{lang.replace('-', '_')}"


def cases() -> list[tuple[str, str, str]]:
    out: list[tuple[str, str, str]] = []
    for code in REPRESENTATIVE_CODES:
        for lang in supported_locale_codes():
            out.append((code, lang, snapshot_name(code, lang)))
    for code, lang, label in FALLBACK_CASES:
        out.append((code, lang, label))
    return out


def write_case(code: str, lang: str, name: str, check: bool) -> list[str]:
    expected = render(code, lang)
    cmd = f"explain {code} --lang {lang}\n"
    must = "\n".join(
        line
        for line in expected.splitlines()
        if line.startswith((
            "error code:",
            "lang:",
            "phase:",
            "message:",
            "cause:",
            "typical cases:",
            "step 1:",
            "correction:",
            "common pitfalls:",
            "fix:",
            "invalid example:",
            "valid example:",
        ))
    ) + "\n"
    paths = {
        "txt": OUT_DIR / f"{name}.txt",
        "cmd": OUT_DIR / f"{name}.cmd",
        "must": OUT_DIR / f"{name}.must",
    }
    stale: list[str] = []
    expected_by_kind = {"txt": expected, "cmd": cmd, "must": must}
    for kind, path in paths.items():
        body = expected_by_kind[kind]
        if check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != body:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(body, encoding="utf-8")
            print(f"[explain-snapshots] wrote {path.relative_to(ROOT)}")
    return stale


def remove_obsolete(expected_names: set[str], check: bool) -> list[str]:
    stale: list[str] = []
    expected_files = {
        OUT_DIR / f"{name}.{suffix}"
        for name in expected_names
        for suffix in ("txt", "cmd", "must")
    }
    for path in OUT_DIR.glob("*"):
        if not path.is_file() or path.suffix not in {".txt", ".cmd", ".must"}:
            continue
        if path not in expected_files:
            if check:
                stale.append(str(path.relative_to(ROOT)))
            else:
                path.unlink()
                print(f"[explain-snapshots] removed {path.relative_to(ROOT)}")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    all_cases = cases()
    stale: list[str] = []
    for code, lang, name in all_cases:
        stale.extend(write_case(code, lang, name, args.check))
    stale.extend(remove_obsolete({name for _, _, name in all_cases}, args.check))

    if stale:
        print("[explain-snapshots][error] stale snapshots")
        for path in stale:
            print(f"- {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
