#!/usr/bin/env python3
from __future__ import annotations

import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TYPECK_DIR = ROOT / "src" / "vitte" / "compiler" / "analysis" / "typeck"
TESTS = ROOT / "src" / "vitte" / "compiler" / "tests" / "typeck_tests.vit"
MANIFEST = ROOT / "src" / "vitte" / "compiler" / "tests" / "typeck_coverage_manifest.json"
REPORT_DIR = ROOT / "target" / "reports" / "typeck_coverage"
SNAPSHOT_DIR = ROOT / "src" / "vitte" / "compiler" / "tests" / "snapshots" / "typeck"
JSON_SNAPSHOT = SNAPSHOT_DIR / "coverage.json.snap"
TEXT_SNAPSHOT = SNAPSHOT_DIR / "coverage.txt.snap"
REMAINING_REPORT = REPORT_DIR / "remaining.md"

SUPPORT_STATUSES = {"supported", "hir_only", "planned", "not_supported"}
OWNER_PHASES = {"resolver", "sema", "typeck", "borrowck"}
EXTERNAL_TESTS = {"typeck-fixtures", "typeck-snapshots", "typeck-gate", "type-system-gate"}


def read(path: Path) -> str:
    if not path.is_file():
        raise SystemExit(f"[typeck-coverage][error] missing file: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8", errors="replace")


def braced_body(text: str, header_pattern: str) -> str:
    match = re.search(header_pattern, text)
    if match is None:
        raise ValueError(f"missing declaration matching {header_pattern!r}")
    start = text.find("{", match.start())
    depth = 0
    for index in range(start, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[start + 1:index]
    raise ValueError(f"unterminated declaration matching {header_pattern!r}")


def pick_variants(text: str, pick_name: str) -> list[str]:
    body = braced_body(text, rf"\bpick\s+{re.escape(pick_name)}\s*\{{")
    return re.findall(r"(?m)^\s*([A-Z][A-Za-z0-9_]*)\s*,?\s*$", body)


def forms(text: str) -> list[str]:
    return re.findall(r"(?m)^\s*form\s+([A-Z][A-Za-z0-9_]+)\s*\{", text)


def test_names(text: str) -> set[str]:
    return set(re.findall(r"(?m)^\s*proc\s+(test_[A-Za-z0-9_]+)\s*\(", text))


def declared_surfaces() -> list[str]:
    surfaces: list[str] = []
    for path in sorted(TYPECK_DIR.glob("*.vit")):
        text = read(path)
        for pick in re.findall(r"(?m)^\s*pick\s+([A-Z][A-Za-z0-9_]+)\s*\{", text):
            if pick.startswith("Type") or pick.startswith("Typeck"):
                surfaces.append(pick)
                for variant in pick_variants(text, pick):
                    surfaces.append(f"{pick}.{variant}")
        for form in forms(text):
            if form.startswith("Type") or form.startswith("ExprType"):
                surfaces.append(form)
    return sorted(set(surfaces))


def remaining_report(payload: dict[str, object]) -> str:
    uncovered = payload["uncovered_surfaces"]
    planned = [
        row for row in payload["coverage_table"]
        if row.get("support_status") in {"planned", "hir_only"}
    ]
    lines = [
        "# Typeck Remaining Coverage",
        "",
        "This report is generated by `tools/typeck_coverage_check.py`.",
        "",
        "## Current State",
        "",
        f"- Declared surfaces: {payload['declared_surface_count']}",
        f"- Manifest entries: {payload['manifest_entry_count']}",
        f"- Supported coverage: {payload['supported_covered']}/{payload['supported_total']}",
        f"- Missing manifest entries: {len(uncovered)}",
        "",
        "## Missing Manifest Entries",
        "",
    ]
    if uncovered:
        lines.extend(f"- `{surface}`" for surface in uncovered)
    else:
        lines.append("- None.")

    lines.extend([
        "",
        "## Planned Or HIR-Only Work",
        "",
    ])
    if planned:
        for row in planned:
            lines.append(
                f"- `{row['variant']}` ({row['support_status']}): "
                f"{row['evidence'].get('assertion', '') if isinstance(row['evidence'], dict) else ''}"
            )
    else:
        lines.append("- None.")

    lines.extend([
        "",
        "## Remaining Hardening Tasks",
        "",
        "- Replace synthetic fixture snapshots with compiler-emitted JSON where the CLI can expose it.",
        "- Add executable negative checks for every invalid fixture once structured Typeck diagnostics are emitted end to end.",
        "- Add multi-file Typeck runs that resolve exported types through the real module loader.",
        "- Compare Typeck diagnostics between CLI check, build and LSP renderers when those entrypoints share the stable diagnostics API.",
        "- Keep `supported` manifest entries gated by a real evidence test and a concrete assertion.",
    ])
    return "\n".join(lines) + "\n"


def evidence_tests(entry: dict[str, object]) -> list[str]:
    evidence = entry.get("evidence", {})
    if isinstance(evidence, dict):
        tests = evidence.get("tests", [])
        if isinstance(tests, list):
            return [str(test) for test in tests]
    return []


def main() -> int:
    tests_text = read(TESTS)
    manifest = json.loads(read(MANIFEST))
    entries = manifest.get("entries", [])
    known_tests = test_names(tests_text) | EXTERNAL_TESTS
    failures: list[str] = []

    required_tests = manifest.get("required_tests", [])
    for name in required_tests:
        if name not in known_tests:
            failures.append(f"missing required typeck test `{name}`")
        elif name.startswith("test_") and f"if not {name}()" not in tests_text:
            failures.append(f"typeck test `{name}` is not called by run_all_tests")

    covered = set()
    rows = []
    supported_total = 0
    supported_covered = 0
    for index, entry in enumerate(entries):
        variant = str(entry.get("variant", ""))
        tests = entry.get("tests", [])
        status = str(entry.get("support_status", ""))
        owner_phase = str(entry.get("owner_phase", ""))
        evidence = entry.get("evidence", {})
        if not variant:
            failures.append(f"entry {index} has no variant")
        if variant in covered:
            failures.append(f"duplicate manifest entry `{variant}`")
        covered.add(variant)
        if status not in SUPPORT_STATUSES:
            failures.append(f"{variant}: invalid or missing support_status `{status}`")
        if owner_phase not in OWNER_PHASES:
            failures.append(f"{variant}: invalid or missing owner_phase `{owner_phase}`")
        if not isinstance(tests, list):
            failures.append(f"{variant}: tests must be a list")
            tests = []
        if not isinstance(evidence, dict) or not evidence.get("assertion"):
            failures.append(f"{variant}: missing evidence assertion")
        if evidence_tests(entry) != tests:
            failures.append(f"{variant}: evidence tests must match tests")
        if status == "supported":
            supported_total += 1
            if tests:
                supported_covered += 1
            else:
                failures.append(f"{variant}: supported entry has no evidence test")
        for test in tests:
            if test not in known_tests:
                failures.append(f"{variant}: unknown test `{test}`")
        rows.append({
            "variant": variant,
            "source": entry.get("source", ""),
            "producer": entry.get("producer", ""),
            "consumer": entry.get("consumer", ""),
            "support_status": status,
            "owner_phase": owner_phase,
            "tests": tests,
            "evidence": evidence,
            "covered": bool(tests),
        })

    declared = declared_surfaces()
    uncovered = sorted(surface for surface in declared if surface not in covered)
    if uncovered:
        failures.append("typeck surfaces missing manifest entries: " + ", ".join(uncovered))

    rows.sort(key=lambda row: row["variant"])
    payload = {
        "schema": "vitte.compiler.typeck_coverage",
        "schema_version": "1.0.0",
        "status": "fail" if failures else "pass",
        "declared_surface_count": len(declared),
        "covered_surface_count": len([surface for surface in declared if surface in covered]),
        "manifest_entry_count": len(covered),
        "supported_total": supported_total,
        "supported_covered": supported_covered,
        "uncovered_surfaces": uncovered,
        "coverage_table": rows,
        "failures": failures,
    }

    lines = [
        "# Typeck Coverage",
        "",
        "| Surface | Status | Owner | Source | Tests | Evidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        evidence = row["evidence"].get("assertion", "") if isinstance(row["evidence"], dict) else ""
        lines.append(
            f"| {row['variant']} | {row['support_status']} | {row['owner_phase']} | "
            f"{row['source']} | {', '.join(row['tests'])} | {evidence} |"
        )
    lines.extend(["", "## Uncovered Surfaces", ""])
    lines.extend(f"- `{surface}`" for surface in uncovered)
    text_snapshot = "\n".join(lines) + "\n"

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    (REPORT_DIR / "coverage.md").write_text(text_snapshot, encoding="utf-8")
    snapshot_payload = {key: payload[key] for key in (
        "schema",
        "schema_version",
        "declared_surface_count",
        "covered_surface_count",
        "manifest_entry_count",
        "supported_total",
        "supported_covered",
        "uncovered_surfaces",
        "coverage_table",
    )}
    json_snapshot = json.dumps(snapshot_payload, ensure_ascii=True, indent=2, sort_keys=True) + "\n"
    (REPORT_DIR / "coverage.json.snap").write_text(json_snapshot, encoding="utf-8")
    (REPORT_DIR / "coverage.txt.snap").write_text(text_snapshot, encoding="utf-8")
    if not JSON_SNAPSHOT.is_file():
        failures.append(f"missing typeck JSON snapshot: {JSON_SNAPSHOT.relative_to(ROOT)}")
    elif JSON_SNAPSHOT.read_text(encoding="utf-8") != json_snapshot:
        failures.append(f"typeck JSON snapshot drift: {JSON_SNAPSHOT.relative_to(ROOT)}")
    if not TEXT_SNAPSHOT.is_file():
        failures.append(f"missing typeck text snapshot: {TEXT_SNAPSHOT.relative_to(ROOT)}")
    elif TEXT_SNAPSHOT.read_text(encoding="utf-8") != text_snapshot:
        failures.append(f"typeck text snapshot drift: {TEXT_SNAPSHOT.relative_to(ROOT)}")

    payload["status"] = "fail" if failures else "pass"
    payload["failures"] = failures
    (REPORT_DIR / "coverage.json").write_text(json.dumps(payload, ensure_ascii=True, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    REMAINING_REPORT.write_text(remaining_report(payload), encoding="utf-8")
    print(
        "[typeck-coverage] "
        f"status={payload['status']} covered={payload['covered_surface_count']} "
        f"declared={payload['declared_surface_count']} entries={payload['manifest_entry_count']} "
        f"supported={payload['supported_covered']}/{payload['supported_total']} "
        f"report={REPORT_DIR.relative_to(ROOT)}/coverage.json"
    )
    for failure in failures:
        print(f"[typeck-coverage][error] {failure}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
