#
# 1126 systems
#

MFAIRS = dopey.u bombur.u

MFLOWS = gloin.u

COMETS = sweet.u

all:V: $MFAIRS $MFLOWS $COMETS

$MFAIRS:V:
	cc=$cc mk -f ../lib/mk.mfair $target

$MFLOWS:V:
	cc=$cc mk -f ../lib/mk.mflow $target

$COMETS:V:
	cc=$cc mk -f ../lib/mk.comet $target
