#
# 1121 systems
#

all:V: fry.u gauss.u sid.u shannon.u

fry.u:V:
	cc=$cc mk -f ../lib/mk.naut $target

gauss.u:V:
	cc=$cc mk -f ../lib/mk.naut $target

sid.u:V:
	cc=$cc mk -f ../lib/mk.mfair $target

shannon.u:V:
	cc=$cc mk -f ../lib/mk.mfair $target
