name: Docs & Graph

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
          sudo apt-get update && sudo apt-get install -y graphviz jq
      - name: Build MkDocs site
        run: mkdocs build --site-dir site
      - name: Generate dependency graph
        run: |
          mkdir -p artifacts
          ./scripts/pro/graph-deps.sh | tee artifacts/deps.dot
          if command -v dot >/dev/null 2>&1; then
            dot -Tsvg artifacts/deps.dot -o artifacts/deps.svg
          fi
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site
      - name: Upload dependency graph
        uses: actions/upload-artifact@v4
        with:
          name: dependency-graph
          path: artifacts
