#
# 1122 systems
#

NAUTS = hunny.u

MFAIRS = gimli.u

MFLOWS = balin.u bashful.u bifur.u bofer.u doc.u dopey.u dori.u dwalin.u gloin.u grumpy.u happy.u siriusb.u sleepy.u tattoo.u thorin.u

COMETS = sweet.u icarus.u jones.u

all:V: $NAUTS $MFAIRS $MFLOWS $COMETS

$NAUTS:V:
	mk -f ../lib/mk.naut $target

$MFAIRS:V:
	mk -f ../lib/mk.mfair $target

$MFLOWS:V:
	mk -f ../lib/mk.mflow $target

$COMETS:V:
	mk -f ../lib/mk.comet $target
