[package]
name = "vitte-inc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Moteur d'incrémentalité pour le compilateur et l'IDE Vitte."
repository = "https://github.com/vitte-lang/vitte"
homepage = "https://github.com/vitte-lang/vitte"
documentation = "https://docs.rs/vitte-inc"
readme = "README.md"
keywords = ["vitte", "incremental", "build", "compiler", "dependency"]
categories = ["development-tools", "compilers"]
exclude = ["/tests", "/examples", "/target", "/.github"]

[lib]
name = "vitte_inc"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.10"
